🆕🎨 Misc styling III
cowprotocol/cowswap pull request #1416
Opened 2022-11-16 13:59 UTC by fairlighteth

# Summary

Misc. styling updates:
- Addresses some items from https://github.com/cowprotocol/cowswap/issues/1408 

<img width="672" alt="Screen Shot 2022-11-16 at 13 58 40" src="https://user-images.githubusercontent.com/31534717/202200187-cfa777d5-908a-461e-b96e-97b7a6e52388.png">
<img width="643" alt="Screen Shot 2022-11-16 at 13 58 29" src="https://user-images.githubusercontent.com/31534717/202200226-46ee3bcb-00ec-4822-ac26-6ec58f98cf69.png">

2022-11-16 14:38 UTC, elena-zh commented
Hey @fairlighteth , great job!
I checked issues that are fixed in t #1408 (1, 2, 3, 5, 8, 9), and added 12 case there: 
![image](https://user-images.githubusercontent.com/70885163/202209223-f578c627-aa28-4fd0-9a94-663f48bc957b.png)

Besides, I have a question related to the 9 case: is this OK that the exclamation sign icon is a white one in the dark mode? In the light mode the warning and the icon have the same color:
![price updated exclamation](https://user-images.githubusercontent.com/70885163/202209571-9f511e0c-6219-450a-ae91-ba39b6ec10a8.png)

Thanks!

2022-11-17 11:57 UTC, fairlighteth commented on src/cow-react/modules/swap/pure/warnings.tsx
> -      <NetworkAlert />
To a different (inner) spot https://github.com/cowprotocol/cowswap/pull/1416/files#diff-6cdd19c6239200a099a1a6f28a4dd43cbf1158a4ae8d89f5ea815d5b4ce364de

2022-11-17 12:01 UTC, alfetopito approved these changes

2022-11-17 12:38 UTC, elena-zh requested changes
Hey @fairlighteth , I can see Swap button disabled in the PR when a warning is displayed in regular mode (no box to check it in the warning to enable Swap button)
![image](https://user-images.githubusercontent.com/70885163/202448215-3cb42615-87cc-4989-a251-7fbdebd2b61f.png)
Modes behavior is mixed up here: 
![image](https://user-images.githubusercontent.com/70885163/202448342-d14d5f76-109d-4929-a38d-a863954105f3.png)

2022-11-17 13:23 UTC, fairlighteth commented
@elena-zh Fixed it now

2022-11-17 13:34 UTC, elena-zh commented
@fairlighteth , yes, thank you!
Could you please also enhance this warning or I need to open a separate issue for this? 
![image](https://user-images.githubusercontent.com/70885163/202460134-677f072f-1200-4364-998d-87ed29358273.png)

2022-11-17 15:57 UTC, elena-zh approved these changes
I have created #1432 issue to enhance Price impact warning

2022-11-17 15:57 UTC, merged