Update cookie policy
cowprotocol/cowswap pull request #1793
Opened 2022-12-23 12:26 UTC by nenadV91

# Summary

This PR updates and enables Cookie Policy page
https://docs.google.com/document/d/1VHltjyMR2ubWToWqdCzgyIsjl4nEhQEucwQ27HdYxBY/edit#

# To test
- go to `/cookie-policy` page
- make sure the content is correct as defined in the doc

2022-12-23 12:33 UTC, nenadV91 commented on src/cow-react/pages/CookiePolicy/CookiePolicy.md
> +![cookie-policy-1.png](https://raw.githubusercontent.com/cowprotocol/cowswap/088e9ef3f018804be9850c0fc65fa3eea26c88d6/src/custom/assets/cow-swap/cookie-policy/cookie-policy-1.png)
These links should be updated with image links from `main` branch once these images are there.

2022-12-23 13:05 UTC, elena-zh requested changes
Hey @nenadV91 , great!

Some issues I faced: 
1. The same as for Privacy policy, it would be great to have a different icon for the Cookie policy in the menu
![image](https://user-images.githubusercontent.com/70885163/209339767-77e55822-21aa-418a-8c01-ae5a383d9507.png)

2. We should use the same format for all 'Last updated' sentences across all content pages (TC, PP, CP). So it would be great to make it look the same like on the Terms page, + add Last, remove parentheses: 
![cookie last](https://user-images.githubusercontent.com/70885163/209339937-e115100a-7e8e-4968-9aaa-96f1ba290f7b.png)
![last upd](https://user-images.githubusercontent.com/70885163/209339941-35336ab1-eb2e-48c5-9fa1-68fe9ce5bb6d.png)
3. I don't think we need an additional background area for paragraphs. I think, we need to use the same format for all content pages (no additional bg): 
![no need in bg](https://user-images.githubusercontent.com/70885163/209340140-45c1fc86-f95b-4836-af40-b81d8419e5e3.png)
4. Do we really need to highlight it in red? It is not highlighted in the doc:
![not in red](https://user-images.githubusercontent.com/70885163/209340288-02acab1f-5773-4630-bc4f-f3348719b588.png)
5. There are no screenshots in Chrome + Win11, desktop version (but I'm able to see them on mobile view)
![no tables](https://user-images.githubusercontent.com/70885163/209340468-9501bbc2-3f8e-4793-9ea1-813ff825c635.png)
6. For me, it is difficult to scroll the table: long press selects and highlights the text, but does not scroll the table content. Can we add a scroll effect on the long press action? 
![image](https://user-images.githubusercontent.com/70885163/209340698-392e4a93-2fdc-417b-9721-8160c228bffc.png)
7. It would be great to enhance the scroll bar itself in Win11
![image](https://user-images.githubusercontent.com/70885163/209340842-4553917f-ed83-491d-9b12-2243d4de8aa7.png)
8. The table in a mobile view does not look good: 
![image](https://user-images.githubusercontent.com/70885163/209340926-8a56a536-1334-4aa0-ac46-d703d7c7e17b.png)
9. Some links exceed the screen width in a mobile view:
![image](https://user-images.githubusercontent.com/70885163/209340997-b734eeee-d6c2-4846-a798-978a967a8b02.png)

Thanks!

2023-01-02 15:37 UTC, alfetopito commented
From Chris on [this thread](https://cowservices.slack.com/archives/C036239R2QL/p1672672303108169?thread_ts=1669300269.450959&cid=C036239R2QL)

> I don’t think the Cookie Policy needs the screenshot - this was only in the google doc to inform what the table needs to have included.

2023-01-05 14:45 UTC, alfetopito approved these changes
I've removed screenshots as requested by Chris

@nenadV91 please address remaining points raised by Elena when you are back


Will merge as is for now

2023-01-05 14:45 UTC, merged

2023-01-09 11:58 UTC, elena-zh commented
> I've removed screenshots as requested by Chris
> 
> @nenadV91 please address remaining points raised by Elena when you are back
> 
> Will merge as is for now

I have created #1825 task for the issues I listed above.