Mograte to the high-availability RPC for Gnosis chain
cowprotocol/cowswap pull request #1837
Opened 2023-01-10 14:14 UTC by shoom3301

# Summary

![image](https://user-images.githubusercontent.com/7122625/211573604-a77e4807-6937-4b62-9ba5-6bb20d05a5a9.png)

The old (https://rpc.gnosischain.com/) Gnosis chain RPC endpoint is not stable and gets down sometimes.
Corresponding to https://docs.gnosischain.com/tools/rpc/#gateway we should https://rpc.gnosis.gateway.fm endpoint, because it provides a high-availability public RPC as part of their Core Contributor agreement in [GIP-70].

  # To Test

1. Connect any wallet to `Gnosis chain` via `Walletconnect`
2. Wait 1-2 minutes
3. AR: Balances disappears, lots of errors in the console
4. ER: No huge errors in the console, balances are displayed well

2023-01-10 14:37 UTC, alfetopito approved these changes

2023-01-10 14:45 UTC, elena-zh requested changes
Hey @shoom3301 , great job!
Balances are loaded nicely when connect to a WC wallet. 
However, now I'm experiencing issues with MM: balances are not loaded there
![MM](https://user-images.githubusercontent.com/70885163/211581794-e0fb21b8-3f14-4ed7-9ec1-baf5f6ca0e78.png)
And it is impossible to add GC network to MM (if it does not present there)
![add GC](https://user-images.githubusercontent.com/70885163/211581934-332e447f-3141-4544-8555-ca874b7725d7.png)

Could you please take a look into these issues?

2023-01-11 09:08 UTC, shoom3301 commented
@elena-zh thanks! Fixed!

2023-01-11 11:46 UTC, closed without merging

2023-01-11 13:33 UTC, alfetopito commented
Why was this branch closed?