Add alpha wallet option and remove Fortmatic
cowprotocol/cowswap pull request #2057
Opened 2023-02-23 15:57 UTC by nenadV91

# Summary

Fixes #2050

Adds alpha wallet option based on wallet-connect
Removes Fortmatic wallet option

<img width="495" alt="Screenshot 2023-02-23 at 16 56 57" src="https://user-images.githubusercontent.com/34926005/220961089-afa17ef1-405a-484d-9a90-2c250eaa77af.png">

2023-02-24 10:56 UTC, elena-zh requested changes
Hey @nenadV91 , nice!

Some notes: 
1. Wallet icon is too tiny on the Connect wallet modal
![logo](https://user-images.githubusercontent.com/70885163/221158590-c80b5c80-fd50-422b-9e73-175ef12472e6.png)

2. It would be great to show the wallet icon on waiting modals(currently. we show WC icon instead)
![alph](https://user-images.githubusercontent.com/70885163/221161541-d07324d1-29ff-4c23-b1ae-db096a3b3112.png)
3. (very impotrant): I can't place swap/limit orders being connected to this wallet:
![order](https://user-images.githubusercontent.com/70885163/221161705-e61dc562-1cff-4c46-b9f1-e794a9cdc37e.png)
![image](https://user-images.githubusercontent.com/70885163/221161822-7e8c7aba-5740-4976-afd9-f519cdae374f.png)
4. Impossible to connect the wallet when Mainnet is not selected (enabled) there (however, it should be the wallet's issue)

2023-02-24 11:42 UTC, elena-zh commented
As for mobile version, some similar notes I left in https://github.com/cowprotocol/cowswap/pull/2044#issuecomment-1441911875


OR can we navigate a user into wallet's integrated browser (like we do for mobile MM or Coinbase) when press on the Alpha button?

2023-02-27 15:44 UTC, nenadV91 commented
@elena-zh 
1 and 2 should be fixed now
3. I've also tried on gnosis chain. Approve and wrap/unwrap works but not swap/limit orders

2023-02-28 09:42 UTC, elena-zh commented
Hey @nenadV91 , case 2 is still reproducible. 
Case 1 LGTM!

Some more details for the case 3: I can sign transactions when open CoW Swap inside their wallet in an integrated browser. So the issue is relevant for WC only.

2023-02-28 10:25 UTC, nenadV91 commented
@elena-zh I've disabled this wallet option in wallet modal also in integrated browsers.
For the case 2 this is what I see
![Screenshot 2023-02-28 at 11 24 08](https://user-images.githubusercontent.com/34926005/221826786-d48a78ad-8f9b-4137-9e40-4e656bf191cb.png)

2023-02-28 11:49 UTC, elena-zh commented
Hey @nenadV91 , I have cleared out my local storage and did hard reloads several times, but still I see this icon :( 
![image](https://user-images.githubusercontent.com/70885163/221845623-8261590a-409f-491b-8108-f6a5c5be7d03.png)

Anyways, I can't approve the PR until we resolve the issue with orders signing :(

2023-03-01 16:33 UTC, alfetopito commented
> @elena-zh 1 and 2 should be fixed now 3. I've also tried on gnosis chain. Approve and wrap/unwrap works but not swap/limit orders

@nenadV91 Since this wallet definitely doesn't work, we should add to the list of unsupported wallets

https://github.com/cowprotocol/cowswap/blob/c2ed0796ff810ce060a7656021f4f3a9c1a6cbe3/src/custom/constants/index.ts#L53

2023-03-01 18:09 UTC, elena-zh commented
> > @elena-zh 1 and 2 should be fixed now 3. I've also tried on gnosis chain. Approve and wrap/unwrap works but not swap/limit orders
> 
> @nenadV91 Since this wallet definitely doesn't work, we should add to the list of unsupported wallets
> 
> https://github.com/cowprotocol/cowswap/blob/c2ed0796ff810ce060a7656021f4f3a9c1a6cbe3/src/custom/constants/index.ts#L53

Hey @alfetopito , I should mention that it works when open CoW Swap app inside the wallet in their integrated browser. So it is partially working. Issue with signing orders is reproducible only when connected to it using WC

2023-03-02 08:57 UTC, shoom3301 commented on src/cow-react/modules/account/containers/AccountDetails/index.tsx
> +import { getIsAlphaWallet, getIsAmbireWallet, getIsZengoWallet } from '@src/custom/connection/utils'
```suggestion
import { getIsAlphaWallet, getIsAmbireWallet, getIsZengoWallet } from 'connection/utils'
```

2023-03-02 08:57 UTC, shoom3301 approved these changes

2023-03-02 10:16 UTC, alfetopito commented
> > > @elena-zh 1 and 2 should be fixed now 3. I've also tried on gnosis chain. Approve and wrap/unwrap works but not swap/limit orders
> > 
> > 
> > @nenadV91 Since this wallet definitely doesn't work, we should add to the list of unsupported wallets
> > https://github.com/cowprotocol/cowswap/blob/c2ed0796ff810ce060a7656021f4f3a9c1a6cbe3/src/custom/constants/index.ts#L53
> 
> Hey @alfetopito , I should mention that it works when open CoW Swap app inside the wallet in their integrated browser. So it is partially working. Issue with signing orders is reproducible only when connected to it using WC

I see!
In that case I would argue that it should be enabled only when the wallet is injected. Should be blocked when connected via WC IMO.

2023-03-02 10:50 UTC, nenadV91 commented
@alfetopito I would wait a bit with marking it as unsupported. We are trying to communicate the issue to the Alpha wallet team.

2023-03-02 18:07 UTC, nenadV91 commented
Closing this PR in favor of new one https://github.com/cowprotocol/cowswap/pull/2099

2023-03-02 18:07 UTC, closed without merging