Feature/limit UI - Small sell amount/high fee warning on limit orders widget
cowprotocol/cowswap pull request #2155
Opened 2023-03-21 18:11 UTC by alfetopito

# Summary

Implements the fee warning banner on limit orders widget

![image](https://user-images.githubusercontent.com/43217/226702343-db4b1d2b-8f25-4f04-9782-8dc5eb60eab9.png)

Currently displayed when current estimated fee > 10% of selected sell amount

# To Test

1. On limit orders page, select a pair
2. Pick a small sell amount (you might need to adjust for the network conditions)
* The warning will be shown when current fee is > 10% of selected sell amount

2023-03-22 11:50 UTC, nenadV91 approved these changes
Codewise LGTM 👍

2023-03-23 12:19 UTC, elena-zh requested changes
Hey @alfetopito , great job!

Some issues I faced: 
1. I think that it would be great not to highlight a fee token in the warning (like it is done in #2163 )
2. Learn more link: where it should navigate to? Also, I'd add an arrow to the link like we do everywhere else in the app 
![image](https://user-images.githubusercontent.com/70885163/227200009-7f1bcc9f-93ee-4627-acbf-491ff2b636b8.png)
3. In a mobile view warning icon is too small. Can we increase its size like we do for the icon at the bottom? 
![icon size](https://user-images.githubusercontent.com/70885163/227200209-5c54b010-d9fb-4d92-8fdb-c8efc260fff2.png)
4. I don't think it is a great idea to show a warning when a fee >100%. For this case we disable 'Review' button and change a message to 'Sell amount is too small'. Anyways, we have an enhancement proposal for this text in https://github.com/cowprotocol/cowswap/issues/1923#issuecomment-1404899067 . It would be great to implement this. 
5. WDYT about adding the same warning (fee>100%) for but orders? 
![image](https://user-images.githubusercontent.com/70885163/227200842-996b23fe-f0b6-411b-bf96-298303eb7f8b.png)
6. I noticed that sometimes fee amount in the warning is not updated in time. See the screenshot: sell amount is grater than fee, and Review button should be enabled, but it is still disabled
![image](https://user-images.githubusercontent.com/70885163/227201671-0d7b093a-837f-42b4-9ab7-e0d3e827df87.png)
![image](https://user-images.githubusercontent.com/70885163/227201813-0d82ab31-e5f6-4e61-8d98-8e84efdf1c97.png)
Can we fix this somehow? 

Thanks!

2023-03-23 17:08 UTC, alfetopito commented
> Hey @alfetopito , great job!
> 
> Some issues I faced:
> 
>     1. I think that it would be great not to highlight a fee token in the warning (like it is done in #2163 )

Now that that PR was merged, this one is fixed as well

>     2. Learn more link: where it should navigate to? Also, I'd add an arrow to the link like we do everywhere else in the app

Since we don't have a text for this yet, I have hidden it

> 
>     3. In a mobile view warning icon is too small. Can we increase its size like we do for the icon at the bottom?

I'll delegate this one to @fairlighteth when he has time, which means won't happen in the short future.
Can you create an issue for that?

> 
>     4. I don't think it is a great idea to show a warning when a fee >100%. For this case we disable 'Review' button and change a message to 'Sell amount is too small'. Anyways, we have an enhancement proposal for this text in [#1923 (comment)](https://github.com/cowprotocol/cowswap/issues/1923#issuecomment-1404899067) . It would be great to implement this.

Done

>     5. WDYT about adding the same warning (fee>100%) for but orders?

Done

>     6. I noticed that sometimes fee amount in the warning is not updated in time. See the screenshot: sell amount is grater than fee, and Review button should be enabled, but it is still disabled
>        Can we fix this somehow?

This is based on the backend response (and only for sell orders) and I can't tell exactly what's their criteria for what is a small orders. Maybe it's $ volume.
Anyway, nothing that can be done on the frontend at this point

2023-03-23 20:04 UTC, elena-zh commented
Hey @alfetopito , great, thank you!
Case 1-2 LGTM, I have created #2172 issue for the case 3. 

As for the case 4, I noticed that the small order banner do not appear on the 1st order. I mean: open Limit orders for the 1st time, select to sell 1 COW per WETH: you will see disabled 'Sell amount is too small' disabled button without a banner. 
![no banner](https://user-images.githubusercontent.com/70885163/227337449-548be5eb-d9e5-4666-b14e-816c4322de28.png)

Also, I had one more proposal to change a bit logic of showing the banner when fees >100% of the sell amount (for buy and sell orders): Instead of `'Small orders are unlikely to be executed. For this order, network fees would be 2715.30% (0.005148 WETH) of your sell amount! Therefore, your order is unlikely to execute.'` banner show `'Sell amount too low. After fees, you would likely lose money from executing this trade.'`, and keep 'Review limit order' button disabled (instead of showing on it 'Sell amount is too small' message. 
![image](https://user-images.githubusercontent.com/70885163/227339008-7bd82bed-c1c2-4cbc-b6fa-af640fa1a4c6.png)

Again, if it requires a lot of effort, we can leave the current changes as they are. 

Thanks

2023-03-24 09:38 UTC, anxolin reviewed
Are the numbers correct?

<img width="799" alt="image" src="https://user-images.githubusercontent.com/2352112/227482868-bee54f34-c74b-480a-8663-ab59414cb6e4.png">

2023-03-24 09:46 UTC, anxolin reviewed
This function is called "percent difference", however is implementing a ration, not a "relative difference)

<img width="636" alt="image" src="https://user-images.githubusercontent.com/2352112/227484310-22bca867-ae87-4d60-9399-6606cd234ee0.png">


Relative difference:
https://en.wikipedia.org/wiki/Relative_change_and_difference

Also, I found the params a bit confusing. Is the delta expected to be already the difference? 

<img width="658" alt="image" src="https://user-images.githubusercontent.com/2352112/227484945-4caab76e-19c3-455f-a9d2-778251846753.png">

IMO you should provide the value and the reference, so you show the relative difference

2023-03-24 14:39 UTC, alfetopito commented
> This function is called "percent difference", however is implementing a ration, not a "relative difference)
> 
> <img alt="image" width="636" src="https://user-images.githubusercontent.com/2352112/227484310-22bca867-ae87-4d60-9399-6606cd234ee0.png">
> 
> Relative difference: https://en.wikipedia.org/wiki/Relative_change_and_difference
> 
> Also, I found the params a bit confusing. Is the delta expected to be already the difference?
> 
> <img alt="image" width="658" src="https://user-images.githubusercontent.com/2352112/227484945-4caab76e-19c3-455f-a9d2-778251846753.png">
> 
> IMO you should provide the value and the reference, so you show the relative difference

It's possible I have not used the right terms, but the way it's coded it's what I want to get.

The question that I made was: how much in % of the sell amount is the fee amount?

For that I have the simple formula:

Sell Amount (SA) = 100%
Fee Amount (FA) = x

=> x = FA*100/SA

Which is what we have right now, using SA as `reference`, and FA as `delta`

Again, probably the fn name/parameters are not the right ones and should be renamed, but I believe the behaviour is correct.

What do you think?

2023-03-24 16:23 UTC, alfetopito commented
> Hey @alfetopito , great, thank you! Case 1-2 LGTM, I have created #2172 issue for the case 3.
> 
> As for the case 4, I noticed that the small order banner do not appear on the 1st order. I mean: open Limit orders for the 1st time, select to sell 1 COW per WETH: you will see disabled 'Sell amount is too small' disabled button without a banner. ![no banner](https://user-images.githubusercontent.com/70885163/227337449-548be5eb-d9e5-4666-b14e-816c4322de28.png)

When that happens, I believe it's because of the backend response.
We ask for a quote and it returns an error with saying that the sell amount is too low.
We do not know what's the fee amount, so we can't tell how much it was compared to the sell amount.
 
> Also, I had one more proposal to change a bit logic of showing the banner when fees >100% of the sell amount (for buy and sell orders): Instead of `'Small orders are unlikely to be executed. For this order, network fees would be 2715.30% (0.005148 WETH) of your sell amount! Therefore, your order is unlikely to execute.'` banner show `'Sell amount too low. After fees, you would likely lose money from executing this trade.'`, and keep 'Review limit order' button disabled (instead of showing on it 'Sell amount is too small' message. ![image](https://user-images.githubusercontent.com/70885163/227339008-7bd82bed-c1c2-4cbc-b6fa-af640fa1a4c6.png)

I'm reluctant to use that wording because it's a limit order and the fee is variable. Their sell amount will always be constant. They won't be losing money per se. What will happen is that the price must be much better than their limit price, so the order is unlikely to fill.
 
> Again, if it requires a lot of effort, we can leave the current changes as they are.
> 
> Thanks

2023-03-24 16:28 UTC, anxolin commented
> Again, probably the fn name/parameters are not the right ones and should be renamed, but I believe the behaviour is correct.

Ok, you want the Ratio https://en.wikipedia.org/wiki/Ratio

It's also fair. Lets leave it as you say then

2023-03-24 16:29 UTC, anxolin approved these changes

2023-03-24 16:35 UTC, elena-zh commented
> When that happens, I believe it's because of the backend response.
> We ask for a quote and it returns an error with saying that the sell amount is too low.
> We do not know what's the fee amount, so we can't tell how much it was compared to the sell amount.

2023-03-24 16:42 UTC, elena-zh commented
> When that happens, I believe it's because of the backend response.
> We ask for a quote and it returns an error with saying that the sell amount is too low.
> We do not know what's the fee amount, so we can't tell how much it was compared to the sell amount.

@alfetopito , thank you for the explanation. 
Then it looks a bit weird to me when we start showing this message when we play with numbers. I mean, on the page load I don't see this message when I select a small amount to trade, then I change amount or an order type, and then I start to see it. 
![image](https://user-images.githubusercontent.com/70885163/227586866-796fd888-7531-41a8-8fce-a4204972764f.png)
![image](https://user-images.githubusercontent.com/70885163/227587228-9254f905-e26a-486c-9e65-302f67274d94.png)

Also, as I can see on the Swap page, we can receive a min required fee amount, so we can use it for our warning 
![image](https://user-images.githubusercontent.com/70885163/227587650-b394aa86-c8d4-4ff4-9233-fe083da1c653.png)

Anyways, I can create an enhancement task for this to address it later. 

Thanks!

2023-03-24 16:49 UTC, alfetopito commented
> > When that happens, I believe it's because of the backend response.
> > We ask for a quote and it returns an error with saying that the sell amount is too low.
> > We do not know what's the fee amount, so we can't tell how much it was compared to the sell amount.
> 
> @alfetopito , thank you for the explanation. Then it looks a bit weird to me when we start showing this message when we play with numbers. I mean, on the page load I don't see this message when I select a small amount to trade, then I change amount or an order type, and then I start to see it. ![image](https://user-images.githubusercontent.com/70885163/227586866-796fd888-7531-41a8-8fce-a4204972764f.png) ![image](https://user-images.githubusercontent.com/70885163/227587228-9254f905-e26a-486c-9e65-302f67274d94.png)
> 
> Also, as I can see on the Swap page, we can receive a min required fee amount, so we can use it for our warning ![image](https://user-images.githubusercontent.com/70885163/227587650-b394aa86-c8d4-4ff4-9233-fe083da1c653.png)
> 
> Anyways, I can create an enhancement task for this to address it later.
> 
> Thanks!

My guess is that the fee is cached locally, so once you see it it's displayed
But yeah, please create an issue, I unfortunately can't work more on this

2023-03-24 16:56 UTC, alfetopito commented
FYI, I'll merge to the parent to consolidate.
Unless there's a blocking bug, follow up issues will have to go to the backlog

2023-03-24 16:56 UTC, merged

2023-03-27 10:00 UTC, elena-zh commented
> My guess is that the fee is cached locally, so once you see it it's displayed
> But yeah, please create an issue, I unfortunately can't work more on this

Hey @alfetopito , created #2182 issue for this