Wallet modal UI improvements
cowprotocol/cowswap pull request #2201
Opened 2023-03-28 14:31 UTC by nenadV91

# Summary

Just a suggestion for wallet modal UI improvements

<img width="640" alt="Screenshot 2023-03-28 at 16 28 55" src="https://user-images.githubusercontent.com/34926005/228271581-3474057f-6d70-4cdf-be3b-84c83ddad9af.png">

<img width="679" alt="Screenshot 2023-03-28 at 16 29 04" src="https://user-images.githubusercontent.com/34926005/228271631-f1433c26-13fa-468f-8db2-f77e7bb8ac71.png">

<img width="668" alt="Screenshot 2023-03-28 at 16 29 26" src="https://user-images.githubusercontent.com/34926005/228271651-51af158b-e619-485e-9020-5aabdbeea8c9.png">

2023-03-28 15:46 UTC, elena-zh requested changes
Hey @nenadV91 , great proposal!
I wonder what @fairlighteth thinks about it!

Some issues from my side: 
1. In a mobile view the wallets list does not look nice 
![image](https://user-images.githubusercontent.com/70885163/228293450-56011c51-efc8-437d-9a75-56c56855d34d.png)
2. And the same issue that I reported in #2191, #2198: I see a white screen when I open the preview link in a mobile device. 

Thanks!

2023-03-30 14:08 UTC, nenadV91 commented
@elena-zh I think both of them should be fixed now
![Screenshot 2023-03-30 at 16 02 57](https://user-images.githubusercontent.com/34926005/228862873-ffbd4a92-e07b-43a3-8d00-2fea1c9eaf30.png)

2023-03-31 19:11 UTC, anxolin approved these changes
looks way nicer

2023-04-03 06:21 UTC, shoom3301 approved these changes
Great!

2023-04-04 14:15 UTC, merged