Wallet/trezor
cowprotocol/cowswap pull request #2216
Opened 2023-03-30 10:10 UTC by nenadV91

# Summary

Trezor connector WIP

2023-03-30 13:54 UTC, elena-zh commented
Can't test this as I don't have a device. Will let you know when I receive it.

2023-03-31 19:32 UTC, anxolin reviewed
Unfortunatelly It didn't work for me. 

<img width="919" alt="image" src="https://user-images.githubusercontent.com/2352112/229212602-6968130b-5426-4c7e-b696-e6d509f882ef.png">


the connector has quite some code, where did you copy that from? maybe add the link so its easier to understand your approach.

2023-04-03 06:31 UTC, shoom3301 commented on src/cow-react/modules/wallet/web3-react/connectors/Trezor/index.tsx
> +global.process = { browser: true } as any
Why do we need this?

2023-04-03 06:40 UTC, shoom3301 requested changes

2023-04-03 06:40 UTC, shoom3301 commented on src/cow-react/modules/wallet/web3-react/connectors/Trezor/index.tsx
> +const _signTypedData = (eip712Data: any) => {
Please, use a proper type here instead of any

2023-04-03 06:40 UTC, shoom3301 commented on src/cow-react/modules/wallet/web3-react/connectors/Trezor/index.tsx
> +    return (res.payload as any).signature
Please, use a proper type here instead of any

2023-04-03 06:40 UTC, shoom3301 commented on src/cow-react/modules/wallet/web3-react/connectors/Trezor/index.tsx
> +  public provider?: any
Please, use a proper type here instead of any

2023-04-03 06:40 UTC, shoom3301 commented on src/cow-react/modules/wallet/web3-react/connectors/Trezor/index.tsx
> +  protected addRequest(engine: any) {
Please, use a proper type here instead of any

2023-04-03 06:40 UTC, shoom3301 commented on src/cow-react/modules/wallet/web3-react/connectors/Trezor/index.tsx
> +  protected addRequest(engine: any) {
I think we can move it to a function:
```
engine.request = trezorProviderRequestHandler
```

2023-04-03 06:40 UTC, shoom3301 commented on src/cow-react/modules/wallet/web3-react/connectors/Trezor/index.tsx
> +const DEFAULT_MANIFEST_EMAIL = ''
Should we specify a value here?

2023-04-03 06:40 UTC, shoom3301 commented on src/cow-react/modules/wallet/web3-react/connectors/Trezor/index.tsx
> +  public async connectEagerly(): Promise<void> {}
What if call here just `return this.activate()` ?

2023-04-03 06:40 UTC, shoom3301 commented on src/cow-react/modules/wallet/web3-react/connectors/Trezor/index.tsx
> +const DEFAULT_MANIFEST_EMAIL = ''
I see, we pass it from `initializeConnector`, then I think we don't need these default parameters at all

2023-04-14 09:20 UTC, nenadV91 commented
@elena-zh Fixed the issue.

2023-04-14 14:58 UTC, elena-zh commented
Hey @nenadV91 , great job!
I have been able to wrap/unwrap/approve/place and cancel limit and market order. 
However, some issues:
1. There is no icon of the wallet (account and confirmation modals)
![no icon](https://user-images.githubusercontent.com/70885163/232078643-7660f1bb-74b7-4174-a11b-2c7a409302d1.png)
2. When the bridge is not installed, a user is navigated to the Install page. But the CoW Swap shows 'Error' modal. Maybe we should show 'connecting' state instead until a user loads and installs the bridge? At least, we can change the message in our modal to 'Please install the bridge and try again'
![trezor suit](https://user-images.githubusercontent.com/70885163/232079063-3b1105b3-730b-474d-9e50-cdddbda4730e.png)
3. Wallet icon is hardly visible on the connect wallet modal in the dark mode
![dark mode](https://user-images.githubusercontent.com/70885163/232079246-1ac28b4d-69c4-425a-a305-2844acbfd8b4.png)
4. it would be great to disable the button for the mobile view:
![image](https://user-images.githubusercontent.com/70885163/232079633-ba1510a2-77d5-490e-a7e8-26ca0db4cee8.png)
5. The wallet is disconnected when refresh the page
6. Also I noticed that I'm navigated to the 'Approve bridge connection' screen each time when I navigate from the Swap to the Limit page and back
7. It would be nice to disable the network selector as it is impossible to switch networks using it: it navigates to the 'Approve bridge connection' screen, and returns a user back to the CoW Swap Mainnet after approving.

Thanks!

2023-08-08 13:44 UTC, closed without merging