refactor: remove affiliate section and related logic
cowprotocol/cowswap pull request #2336
Opened 2023-04-18 16:41 UTC by tukantje

# Summary

Fixes #2300 

Removes affiliate banners, faq section, account section.

<img width="1183" alt="Screenshot 2023-04-18 at 18 43 37" src="https://user-images.githubusercontent.com/5172699/232846758-2e7589e6-daa5-4541-b27b-bf9b13f5eac7.png">

We leave the code of these components in as we might want it in the future.

# To Test

1. Open CoW Swap
2. Go to accounts
3. Should not see affiliate section
4. Follow an affiliate link (like this https://swap.cow.fi/#/account?referral=0x9FA3c00a92Ec5f96B1Ad2527ab41B3932EFEDa58&chain=mainnet)
5. You should not see affiliate banner
6. Hover over FAQ
7. You should not see affiliate links there
8. Open affiliate page by link (like https://swap.cow.fi/#/faq/affiliate?chain=mainnet)
9. You should get 404

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

2023-04-19 07:43 UTC, shoom3301 commented
@tukantje thank you!

Could you also remove `AffiliateStatusCheck` deps? Like:
 - `getProfileData` from `src/cow-react/api/gnosisProtocol/api.ts`
 - `src/custom/state/affiliate/reducer.ts`
 - and others

2023-04-19 07:44 UTC, shoom3301 approved these changes

2023-04-19 10:25 UTC, alfetopito approved these changes
![](https://i.ytimg.com/vi/L6hEyLmimZs/maxresdefault.jpg)

2023-04-19 12:41 UTC, elena-zh requested changes
Hey @tukantje , great job!
Some nitpicks: 
1. It would be great to remove Affiliate FAQ section inside the FAQ:
![faq affiliate](https://user-images.githubusercontent.com/70885163/233077573-544e8841-d6f6-4c61-9771-b0099eb68db2.png)
2. Should we still display this option in the local storage?
![should we store this](https://user-images.githubusercontent.com/70885163/233077699-d6a271f0-cd52-4b92-89d2-88167cec7ddb.png)
3. Can we remove a referral data from the link?
![remove referral](https://user-images.githubusercontent.com/70885163/233077801-569a84a0-ca51-4ef6-b72e-59377ea56bec.png)

Thank you!

2023-04-19 13:08 UTC, nenadV91 approved these changes

2023-04-20 08:41 UTC, tukantje commented
> @tukantje thank you!
> 
> Could you also remove `AffiliateStatusCheck` deps? Like:
> 
>     * `getProfileData` from `src/cow-react/api/gnosisProtocol/api.ts`
> 
>     * `src/custom/state/affiliate/reducer.ts`
> 
>     * and others

Not fully, not directly.

We need to adjust the state a bit - some state still relies on affiliate state even though it doesn't really belong there. So getting rid of these immediately would break some parts.

2023-04-20 08:51 UTC, tukantje commented
> 

In the original slack discussion, it was mentioned we should leave the code in since we might bring this one back in later on.

2023-04-20 09:29 UTC, alfetopito commented
As Elena pointed out, you missed one spot

![image](https://user-images.githubusercontent.com/43217/233323353-cc33c961-1029-4c52-8ec0-8e5624281569.png)

The affiliate link can still be accessed, and leads to a 404:  https://swap-dev-git-chore-remove-affiliate-section-from-b5dc25-cowswap.vercel.app/#/faq/affiliate?chain=mainnet

2023-04-20 10:55 UTC, tukantje commented
@alfetopito @elena-zh updated the codebase to remove these, thank you.

Regarding local storage part, I've removed the reducer for affiliate now; it should not show up on a clean session.

Regarding the last part about query params, we don't do that for any query parameters (so I can even do the following). So I think it'd expand the scope here.
<img width="1260" alt="Screenshot 2023-04-20 at 12 53 05" src="https://user-images.githubusercontent.com/5172699/233345262-3d8c751b-3acd-4135-a61a-13386896d10d.png">

2023-04-20 11:00 UTC, tukantje commented
Updating naming of the branch to conventional commits style.

2023-04-20 11:37 UTC, elena-zh commented
Hey @tukantje , thank you for the explanation. 
I still can see the Affiliate section in the FAQ
![image](https://user-images.githubusercontent.com/70885163/233354236-e4d6213b-1128-4929-8f3c-ffc0165bcc9d.png)
And the log in the local storage (I have opened it in the Incognito window)
![image](https://user-images.githubusercontent.com/70885163/233354596-480c06be-b748-4062-8eda-f90bbe59958d.png)

2023-04-20 12:31 UTC, tukantje commented
That is weird, since I don't see it locally. Investigating.

2023-04-20 14:21 UTC, elena-zh approved these changes
LGTM!

2023-04-21 09:54 UTC, tukantje commented
@alfetopito all is clear now 🚀

2023-04-21 09:57 UTC, alfetopito commented on src/cow-react/common/hooks/useNotificationState.ts
Is github not updating for me or is this file really part of this PR?

2023-04-21 09:57 UTC, alfetopito commented on src/custom/components/NotificationBanner/index.tsx
This is another file that is unrelated

2023-04-21 10:01 UTC, tukantje commented on src/cow-react/common/hooks/useNotificationState.ts
This is a part of the PR. Related to the file down below, this addresses @shoom3301 's / @elena-zh 's comment.

To be able to remove reducer of affiliate we need to extract a todo (relying on affiliate state on redux instead of something generalised).

2023-04-21 10:02 UTC, tukantje commented on src/custom/components/NotificationBanner/index.tsx
This is a part of the PR. Related to the file down below, this addresses @shoom3301 's / @elena-zh 's comment.

To be able to remove reducer of affiliate we need to extract a todo (relying on affiliate state on redux instead of something generalised).

2023-04-21 13:14 UTC, anxolin commented on src/custom/state/affiliate/hooks.ts
> -  return useAppSelector((state) => (id ? state.affiliate.isNotificationClosed?.[id] ?? false : null))
why any needed?

2023-04-21 15:01 UTC, alfetopito commented on src/cow-react/common/hooks/useNotificationState.ts
Oh I see.
Thanks for the explanation

2023-04-27 04:47 UTC, shoom3301 approved these changes
Awesome! Thank you!

2023-04-27 16:01 UTC, merged