Surplus/usd value
cowprotocol/cowswap pull request #2338
Opened 2023-04-19 12:46 UTC by nenadV91

# Summary

Shows USD value of surplus in confirmation modal and executed order popup if the surplus USD value is larger then 0.01

Confirmation modal
![Screenshot 2023-04-19 at 13 42 11](https://user-images.githubusercontent.com/34926005/233078893-76da69bf-c5b3-4e9e-85e1-dd601b46b902.png)

Executed order popup
<img width="395" alt="Screenshot 2023-04-19 at 14 30 24" src="https://user-images.githubusercontent.com/34926005/233078957-e5a58e8e-d9c8-4274-b4bd-a6e6a46e70ca.png">

# To test
1. Create an order and wait until its executed
2. Don't close the confirmation modal
3. Once the order is executed you will see executed order summary after 4 seconds with USD estimation for surplus and also executed order toast popup also with usd estimation for surplus if its larger then 0.01 USD

2023-04-19 12:49 UTC, nenadV91 commented on src/cow-react/common/pure/ExecutedSummary/index.tsx
> -const SummaryWrapper = styled.div`
Moved this to separate styles file

2023-04-19 12:50 UTC, nenadV91 commented on src/custom/components/OrderProgressBar/index.tsx
> -
Moved this to also to separate file `src/custom/components/TransactionExecutedContent/styled.ts`

2023-04-19 12:51 UTC, nenadV91 commented on src/custom/components/OrderProgressBar/index.tsx
> -function TransactionExecutedContent({
Moved this to separate component `src/custom/components/TransactionExecutedContent/index.tsx`

2023-04-19 14:15 UTC, elena-zh requested changes
Hey Nenad!
Great job!
Can we please add brackets and USD sign for the amount?
![brackets and usd](https://user-images.githubusercontent.com/70885163/233102703-b2d4d007-45c1-4d2e-8f2b-046b251cc0f5.png)
Also, do we need to wrap the value to another line in the pop-up?
![another line](https://user-images.githubusercontent.com/70885163/233103207-21dcecc1-b182-4731-9ec3-73e2c80ae709.png)

Thanks!

2023-04-20 06:40 UTC, shoom3301 approved these changes
Great refactoring! Thank you!

2023-04-20 09:22 UTC, nenadV91 commented
@elena-zh Should be fixed now.
USD value for surplus where the $ sign is before the value is fine because we are using the same component all over the app

2023-04-20 09:31 UTC, alfetopito commented
Hmm the small font looks super odd to me, but I have no better idea.
Can we have @fairlighteth take a look and provide a suggestion?

2023-04-20 11:08 UTC, elena-zh commented
Hey @nenadV91 , great job!
Agree with @alfetopito , that a smaller font looks weird. Maybe we can make it's sixe the same as the main text?
![Uploading fonts.png…]()

Thanks!

2023-04-20 11:56 UTC, nenadV91 commented
@elena-zh @alfetopito Good suggestion, fixed!

2023-04-20 14:27 UTC, nenadV91 commented
@elena-zh Ok I think its fixed now 😄

2023-04-20 15:09 UTC, elena-zh approved these changes
Finally, looks good to me!!

2023-04-20 15:39 UTC, merged