fix(account-modal): fix cancellation tx link for Gnosis Safe
cowprotocol/cowswap pull request #2385
Opened 2023-04-27 15:06 UTC by shoom3301

# Summary

Fixes #2370

2023-04-28 10:32 UTC, elena-zh requested changes
Hey @shoom3301 , great!
When I open the app inside the Safe app, I see the connect link to the cancellation TX. 
However, when I connect to the Safe using WC, I get a link to the etherscan with 404 error:
![image](https://user-images.githubusercontent.com/70885163/235124749-6cb0272e-29d4-4753-b53b-ed0e377ed799.png)

Could you please fix it?

Thanks!

2023-04-28 10:43 UTC, anxolin commented on src/cow-react/modules/account/containers/Transaction/StatusDetails.tsx
> +      ? getSafeWebUrl(chainId, safeTransaction.safe, cancellationHash)
can this be undefined? (since you have a `?` in line 96

2023-04-28 12:46 UTC, anxolin commented on src/cow-react/modules/account/containers/Transaction/StatusDetails.tsx
> +      ? getSafeWebUrl(chainId, safeTransaction.safe, cancellationHash)
👍 make sense

2023-04-28 12:46 UTC, anxolin approved these changes

2023-05-05 07:44 UTC, shoom3301 commented
@elena-zh thanks! Fixed

2023-05-05 08:53 UTC, alfetopito approved these changes

2023-05-05 11:24 UTC, elena-zh approved these changes
Great job!

2023-05-06 05:49 UTC, merged