fix(swap-url-amounts): fix sellAmount and buyAmount url parameters for SWAP
cowprotocol/cowswap pull request #2452
Opened 2023-05-11 14:57 UTC by alfetopito

# Summary

Closes #2449 

Fix `sellAmount` and `buyAmount` url params for Swap

# To Test

1. On Swap, make sure you have a sell token, insert in the url after the token(s): `?sellAmount=1`
* Sell amount input should be set to 1
2. On Swap, make sure you have a buy token, insert in the url after the token(s): `?buyAmount=4`
* Buy amount input should be set to 4

This change touches chainId/recipient (from URL only) related areas, so we also need regression tests for that

# Background

The issue was introduced on https://github.com/cowprotocol/cowswap/pull/2317
When the URL params are set, the state was being updated properly [here](https://github.com/cowprotocol/cowswap/blob/1df31149f10cce2e12d81e23e4f0b3e6b5f9467c/src/cow-react/modules/swap/hooks/useSetupSwapAmountsFromUrl.ts#L16)
But then, when [the hook `useSetupTradeState`](https://github.com/cowprotocol/cowswap/blob/b072133c731d5a61b06d0af37a015b9682869896/src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts#L108) triggered, [it replaced the existing state with a stale version](https://github.com/cowprotocol/cowswap/blob/f5e962a33e35781b1c5546b9684dd42d9c238242/src/cow-react/modules/swap/hooks/useSwapRawState.ts#LL18C22-L18C22) which did not contain the changes from the previous hook `useEffect`

So my solution was to add a new redux action to allow updating part of the state, rather than replacing everything at once

2023-05-11 14:58 UTC, alfetopito commented on src/cow-react/modules/swap/hooks/useSwapRawState.ts
>    const dispatch = useAppDispatch()
This state was stale, not being updated by the time the callback on line `23` was executed.
Resulting in the old overwrite the new state

2023-05-11 15:16 UTC, elena-zh requested changes
Hey @alfetopito , great job!
However, regression issues: 

1. Tokens selection is not cleared out when change network (connected/not connected states): 
paste the link /#/100/swap/wxdai/WETH?buyAmount=15
change the network to mainnet: 
![weth](https://github.com/cowprotocol/cowswap/assets/70885163/e244c8e7-7b0f-4719-b7bc-329e5360c4b6)

2. Connected state: when change the network indicator in the URL, but reject switch network action in the wallet. the network indicator is not returned back in the URL to the currently connected one. The same with an unsupported network: 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/b3ae2b5f-f8ba-4236-aeed-2c4da16d0cd8)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/e987aa89-2d82-4eca-ad53-7c3d04cc7f3b)

Could you please fix this? 

Thanks

2023-05-11 15:48 UTC, anxolin reviewed
Soft approve, you need to convince Elena

2023-05-11 15:52 UTC, alfetopito commented on src/state/swap/reducer.ts
> +        independentField: originalIndependentField,
Copy paste issue, will be removed in the next push

2023-05-12 08:10 UTC, elena-zh approved these changes
I have created #1454 issue for the last case I reported

2023-05-12 09:30 UTC, nenadV91 approved these changes

2023-05-12 09:40 UTC, merged