feat(twap) Feature/twap order defaults
cowprotocol/cowswap pull request #2685
Opened 2023-06-15 17:18 UTC by alfetopito

# Summary

<<if there's an issue>>Fixes #issueNumber

*High-level description of what your changes are accomplishing*

*Add screenshots if applicable. Images are nice :)*

  # To Test

1. <<Step one>> Open the page `about`
- [ ] <<What to expect?>> Verify it contains about information...
- [ ] Checkbox Style list of things a QA person could verify, i.e.
- [ ] Should display Text Input our storybook
- [ ] Input should not accept Numbers
2. <<Step two>> ...

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

2023-06-15 17:44 UTC, anxolin approved these changes
Not part of this PR, but just asking. 

Why do we limit to 100 the number of parts? 
Also, so we will force to have always a right value? I mean, other option is to allow 0,1 or whatever, and inform that the field is not correct , similarly to what we do with the minimum time. 

Im not strongly oppinionated, but in general I feel is better to give freedom in the inputs, so users can make mistakes (as long as we show some error).

<img width="752" alt="image" src="https://github.com/cowprotocol/cowswap/assets/2352112/104e97a2-2ec1-453b-ae46-218c28c79caf">

Feel free to ignore! just thinking aloud

2023-06-16 11:22 UTC, elena-zh requested changes
Hey @alfetopito , nice!
However, I can't enter any number that starts with 1 (11, 12, 10...). 
The same withy 0 (e.g. 08), but not so critical as 10. 

Also, could you please remove the max number of 100? 

And one more thing: there is no arrows in the field
![image](https://github.com/cowprotocol/cowswap/assets/70885163/43c0e951-91d3-47f4-b46c-26268ee7ee47)

Will they be added a bit later? 

Thanks!

2023-06-19 05:18 UTC, shoom3301 approved these changes
Thanks for aligning the code style!

2023-07-05 13:43 UTC, elena-zh commented
Hey @alfetopito , great job!
As a nitpick, could you please remove a decimal placeholder when remove a value in the field? 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/f121bce2-d648-40ac-9643-b9eb6bb72a5c)

Still, max number of 100 parts is not removed  :(

And could you please clarify whether I should  create another task for adding arrows into the Parts fields?

Thank you!

2023-07-05 13:44 UTC, alfetopito commented
> Hey @alfetopito , great job! As a nitpick, could you please remove a decimal placeholder when remove a value in the field? ![image](https://user-images.githubusercontent.com/70885163/251168528-f121bce2-d648-40ac-9643-b9eb6bb72a5c.png)

Will give it a try

> Still, max number of 100 parts is not removed :(

It should not be limited to 100? I thought it should... probably missed that
 
> And could you please clarify whether I should create another task for adding arrows into the Parts fields?

That is browser dependant AFAICT. Like other number fields, don't think we'll ever implement this.

2023-07-05 13:53 UTC, alfetopito commented
100 limit removed, in favor of 100_000 limit 😬 

We can have it unlimited, but then it's possible to break the UI which looks ugly

![image](https://github.com/cowprotocol/cowswap/assets/43217/57db9e2d-2a69-49e2-948a-07b9d237ce7c)

And we don't need more than 100k, do we?

2023-07-05 14:28 UTC, elena-zh approved these changes
Works for me! Thanks

2023-07-05 16:03 UTC, merged