fix(orders-table): display fulfilled status before cancelling
cowprotocol/cowswap pull request #2770
Opened 2023-06-30 14:39 UTC by shoom3301

# Summary

Fixes #2710

2023-06-30 16:01 UTC, elena-zh requested changes
Hey @shoom3301 , something is wrong with orders statuses: as soon as order is signed, all orders  (including the parent one) go to 'Scheduled' status. 
When a part is filled, it is not reflected on the UI until I refresh the page. 
Once refresh, I can see the parent order blinking with 'Open' status, then returning back to 'Scheduled'. 
See the video: https://www.loom.com/share/a7005a46ceac41e1b97c7707c2be1c11

Somehow I caught up the possibility yo cancel the parent order (quickly pressed on the Cancel button for the blinking order), and noticed that the filled part did not change its status. However, the parent order did not show the 'filled' info (33% filled): 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/6442639f-96c8-4af0-93ae-c2a59323990f)

2023-07-03 13:02 UTC, alfetopito approved these changes

2023-07-04 11:07 UTC, shoom3301 commented
@elena-zh it seems to be unrelated to #2710 issue, doesn't it?

2023-07-04 11:13 UTC, elena-zh commented
> @elena-zh it seems to be unrelated to #2710 issue, doesn't it?

Not sure. How can I properly test statuses as I can hardly catch 'Cancel order' button due to all orders are in 'Scheduled' state?

2023-07-05 08:02 UTC, shoom3301 commented
@elena-zh let's do a call, I can't reproduce it

2023-07-05 11:53 UTC, elena-zh commented
Hey @shoom3301 , 
I cleared my local storage and did another round of testing. 
Good news, the 'Filled' order status is not changed when I cancel a parent order!

However. there are some other issues with 'Cancel' feature that I faced: 
1. When a part is in Open state, and I cancel it, once TX is mined the order goes to 'Cancelled' state even if it is filled. Can we leave 'Filled' status for the part even if Cancel TX is successfully executed for the part?
![ffilled](https://github.com/cowprotocol/cowswap/assets/70885163/f125c729-8f6d-4cf7-b565-27e7973b7495)
2. When a parent order is in Cancelling state, its part is still in Scheduled
![not cancelling](https://github.com/cowprotocol/cowswap/assets/70885163/28c38c97-0eee-4c96-b2ef-5327a018f2df)
3. When a scheduled part is cancelled, it navigates to 404 page on Explorer
![cancelled1](https://github.com/cowprotocol/cowswap/assets/70885163/19e96443-7a99-40b4-81b3-44a43ba057e1)

LMK please if I need to open a separate issue on any of these items.

2023-07-06 07:22 UTC, shoom3301 commented
More issues:
https://github.com/cowprotocol/cowswap/pull/2764#issuecomment-1622082461

2023-07-06 11:49 UTC, shoom3301 commented
@elena-zh fixed

2023-07-06 15:52 UTC, elena-zh commented
Hey @shoom3301 , issues that I faced: 
1. When I cancel the past order's part, I see that the parent order hangs in the 'PF' status in the Open orders tab. It should go to the 'History' tab
![cancelled when the last part](https://github.com/cowprotocol/cowswap/assets/70885163/39f7db7c-4bf6-4260-be5e-9eab5f51a1b2)

2. I don't see any pop-ups and sounds here (when an order is placed/filled). Pop-ups appear only when cancel order
3. Time of the parent part is a bit different in comparison with the last its part
![not the same](https://github.com/cowprotocol/cowswap/assets/70885163/70abe4cf-b40b-497d-bc01-ee00e303538f)
4. I created #2802 issue as an edge case when execute a TWAP order TX when it is expired
5. I still can see order's part appearing in the Open order tabs after cancelling the main order 
![cancelled](https://github.com/cowprotocol/cowswap/assets/70885163/80afc773-436b-4f7b-b665-f76afe38fd95)

2023-07-07 11:30 UTC, nenadV91 commented on src/legacy/state/orders/reducer.ts
> +            const children = Object.values(allOrdersMap).filter(
Could you do this in one go, for example:

```javascript
Object.values(allOrdersMap).forEach((item) => {
  if (item?.order.composableCowInfo?.parentId === id) {
    cancelOrderInState(state, chainId, item)
  }
})
```

2023-07-07 11:49 UTC, nenadV91 approved these changes
LGTM 👍

2023-07-07 14:05 UTC, elena-zh approved these changes
Positive flow works fine!
There are still some issues related to edge cases: 
 - #2808 
 - #2809 
 - #2715 
 -  #2792

2023-07-07 15:10 UTC, merged