feat: handle toasts
cowprotocol/cowswap pull request #4023
Opened 2024-03-10 23:26 UTC by anxolin

# Summary

Continues on https://github.com/cowprotocol/cowswap/pull/4022

This PR handles TOAST events, and shows a snackbar.

# To Test

1. Setup "Dapp mode" for the toasts

2. Check that the toast is shown when you do a trade

3. Setup "Self contained" mode for the toasts

3. Check now toasts show in the Dapp only (no snackbars)

2024-03-11 11:29 UTC, elena-zh commented
When I open the PR link to the app (not to the configurator), I don't see connect button at the top, just a line instead 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/3061b3f2-f3cc-4051-a170-fbdc3553fc2c)

2024-03-11 11:34 UTC, elena-zh commented
Explanation toasts are too slow: they are kept to be displayed when I switch the mode, and when I start closing them, I need closing a lot. See the video: https://www.loom.com/share/27fe1b8945e04c718c6020f70fd20141?sid=185a65ee-8f27-4ce5-ae3a-62f8a79cfb87

2024-03-11 11:52 UTC, elena-zh requested changes
And I don't see snackbars when I place orders in the Dapp mode (neither for onchain nor of offhchain TXs)

Besides, when I switch to Self-contain mode, I see all previous notifications for TXs that were done in Dapp mode: 
![all done before](https://github.com/cowprotocol/cowswap/assets/70885163/3b73648e-561b-4866-80f1-a872b27c08f5)

2024-03-11 14:21 UTC, anxolin commented
I'm sorry Elena, there was some changes that I didn't push. So it was not yet connected to the notification logic. I just pushed it. I hope now can be tested

2024-03-12 09:19 UTC, shoom3301 commented on apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
> +      baseUrl: 'https://swap-dev-git-feat-snackbars-from-events-8-cowswap.vercel.app', // TODO: Leave default DEFAULT_BASE_URL,
TODO: revert this after QA

2024-03-12 09:19 UTC, shoom3301 approved these changes

2024-03-13 08:06 UTC, shoom3301 commented
@elena-zh 
1. Fixed. This PR is looking into https://swap-dev-git-feat-snackbars-from-events-8-cowswap.vercel.app which was not up to date.
2. Fixed
3. This is expected, should be done in another PR (after [this one](https://github.com/cowprotocol/cowswap/pull/3934))
4. This is also expected, because the widget preview don't have changes from this PR. It will be solved once we merge everything in one branch
5. For me it's ok

2024-03-13 13:01 UTC, elena-zh approved these changes
Hey @shoom3301 , thanks for the fixes!

@anxolin , here is one question for you: when notifications go one after another, they are hidden under currently displayed one. WDYT about showing snackbars above/at the bottom of the currently displayed one?

2024-03-14 15:15 UTC, merged