refactor: use new snackbars for wrap/unwrap/approve notifications
cowprotocol/cowswap pull request #4038
Opened 2024-03-13 14:03 UTC by shoom3301

# Summary

<<if there's an issue>>Fixes #issueNumber

*High-level description of what your changes are accomplishing*

*Add screenshots if applicable. Images are nice :)*

  # To Test

1. <<Step one>> Open the page `about`
- [ ] <<What to expect?>> Verify it contains about information...
- [ ] Checkbox Style list of things a QA person could verify, i.e.
- [ ] Should display Text Input our storybook
- [ ] Input should not accept Numbers
2. <<Step two>> ...

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

2024-03-14 16:01 UTC, elena-zh requested changes
Hey @shoom3301  , great job!
However: 
1. When placing a SWAP order in Safe, I see 'view on Safe' link instead of 'View on Explorer'
![view on explorer](https://github.com/cowprotocol/cowswap/assets/70885163/d9f2f46c-1326-4cb9-bb95-c4017f705082)
2. For wraps/unwraps when connected to Safe (WC and inside the Safe), also TXs links should be to Etherscan instead of Safe
![safe](https://github.com/cowprotocol/cowswap/assets/70885163/dfbbc392-56d7-4e32-8373-bc406f6524c5)
See how it is on Prod:

![etherscan, not safe](https://github.com/cowprotocol/cowswap/assets/70885163/4d97966b-a485-43ce-bdde-b55f80871e1c)

2024-03-15 04:57 UTC, shoom3301 commented
@elena-zh I can't reproduce the first case.
Do you try a regular swap? Or swap + approve?

<img width="570" alt="image" src="https://github.com/cowprotocol/cowswap/assets/7122625/804a4998-0b40-4ce8-912c-09d09fe784eb">

2024-03-15 05:10 UTC, shoom3301 commented
About the second case.
I think it's event better. For Safe users we always should lead then to Safe transactions, because in a Safe transaction you can find on-chain transaction but otherwise not. 
@anxolin what do you think?

2024-03-15 11:34 UTC, shoom3301 commented
@elena-zh the first case is fixed, thank you!

2024-03-15 13:47 UTC, elena-zh commented
Hey @shoom3301 , thank you!
There is one more case still not addressed: in Safe (inside), the app allows to place a Buy order with ETH as a sell token (runs through bundling flow). It would be great to have 'View on Explorer' link there  instead of the' View on Safe' on the Submitted toas notification
![explorer](https://github.com/cowprotocol/cowswap/assets/70885163/119b6664-ff66-4e45-ab78-35b3cdf1033d)

Also, when I opened the PR preview link today, tons of notifications appeared on the screen, but the wallet appeared to be disconnected. Can we avoid this situation somehow?  I mean, not to show notifications from the previous day or the ones that were displayed on another device?
![image](https://github.com/cowprotocol/cowswap/assets/70885163/11df0440-4c5c-4e0a-bb30-0deb1e1138af)

Thanks

2024-03-15 14:28 UTC, alfetopito approved these changes

2024-03-18 08:53 UTC, shoom3301 commented
@elena-zh thanks! Fixed the first case.
About the second one, yes, it's possible, but I would like to work on it in the next iteration.

2024-03-18 08:54 UTC, shoom3301 commented on apps/cowswap-frontend/src/common/updaters/FinalizeTxUpdater.tsx
> +  }
https://github.com/cowprotocol/cowswap/pull/4039/files#diff-6cc919012b8679e920860edbfee1c224439a6a2aadd41fcce21edce81c446d06L66

It was a part of `soundMiddleware`

2024-03-18 11:39 UTC, elena-zh commented
Hey @shoom3301 , great!
But still I have some nitpicks: 
1. When I cancel a TWAP part (not order, opened part), the notification shows 'View on Safe' link instead of the 'View on Etherscan'. Just to mention, 'View on Safe' for cancelling the main order works fine and looks good
2. At lease 2 times I received a Traded 0 amount notification at a time of cancelling a TWAP part (maybe at the time that the order has been filled, but I initiated the Cancel TX and signed it). 
![cancelling](https://github.com/cowprotocol/cowswap/assets/70885163/18ef495e-87ea-49ca-9f3c-64da04cace80)
3. I placed 2 the same orders, and one of them got stuck in the Opened orders when was filled :( In incognito mode the order goes to History (I assume that the issue is not related to the current PR, so just mentioning) 
![stuck](https://github.com/cowprotocol/cowswap/assets/70885163/2176247b-95f0-404c-8769-9b6c45bb5806)
4. I receive 2 Cancelled order notifications, sometimes for Traded as well. I reported #4053 issue for this
5. I have created #4052 issue for case 2 from my [comment ](https://github.com/cowprotocol/cowswap/pull/4038#issuecomment-1999704419)above

Thanks!

2024-03-18 11:50 UTC, shoom3301 commented
@elena-zh thank you!
1. Fixed
2. This case probably comes out of this task scope, please create another issue for it

2024-03-18 12:38 UTC, elena-zh commented
Created #4054 issue for the 2nd case. 
As for the current fix, Order submitted and Order cancelled links for a parent TWAP order now show View on Etherscan link insteat of 'View on Safe. The etherscan link navigates to 404 page
![safe](https://github.com/cowprotocol/cowswap/assets/70885163/90f6eedb-69c5-4224-bafd-4f1d287ef532)

2024-03-18 14:19 UTC, elena-zh commented
Hey @shoom3301 , still there are some issues: 
1. Cancel parent TWAP order: the link should say 'View on Safe' (now it navigates to 404 Etherscan). Same should be for order creation pop-up. 
2. Cancel TWAP part: the link should say 'View on Explorer' (now it navigates to Safe). Same should be for Filled and Expired notifications.

2024-03-18 15:26 UTC, shoom3301 commented
@elena-zh fixed

2024-03-18 15:42 UTC, elena-zh approved these changes
Great job!

2024-03-19 07:38 UTC, merged