fix(transactions): add expiration time to on-chain txs
cowprotocol/cowswap pull request #4140
Opened 2024-04-02 12:18 UTC by shoom3301

# Summary

Fixes #4044

*High-level description of what your changes are accomplishing*

*Add screenshots if applicable. Images are nice :)*

  # To Test

1. <<Step one>> Open the page `about`
- [ ] <<What to expect?>> Verify it contains about information...
- [ ] Checkbox Style list of things a QA person could verify, i.e.
- [ ] Should display Text Input our storybook
- [ ] Input should not accept Numbers
2. <<Step two>> ...

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

2024-04-02 12:23 UTC, shoom3301 commented on apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts
> +    return 'expired'
To properly display the status in txs history:

<img width="832" alt="image" src="https://github.com/cowprotocol/cowswap/assets/7122625/46ff6720-762d-4445-9cb3-bb5beb1a16de">

2024-04-02 12:26 UTC, shoom3301 commented on apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts
> +            // we need to adjust Transaction object and add "id" + "status" to match Orders type
>to match Orders type

This is very bad idea, Interface segregation principle breach

2024-04-02 12:29 UTC, shoom3301 commented on apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/services/checkOnChainTransaction.ts
> +      setTxLastBlockNumber()
One of ways where we could stuck into Pending... state.
We always must add `lastBlockNumber` to the transaction.

2024-04-02 12:31 UTC, shoom3301 commented on apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/hooks/useShouldCheckPendingTx.ts
> +  if (!tx.lastCheckedBlockNumber) return true
Improved logic here.
There might be a case, when we have never set `lastCheckedBlockNumber` to a transaction and in the same time we have never got `receipt` for it.
In that case the tx will get stuck into `pending` state.

This fix works only with the change:
https://github.com/cowprotocol/cowswap/pull/4140/files#r1547786433

2024-04-02 12:32 UTC, shoom3301 commented on apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/hooks/useShouldCheckPendingTx.ts
> +  // every 3 blocks if pending for longer than 5 minutes
Reduced values:
1 hour -> 5 minutes
5 minutes -> 1 minute

2024-04-02 12:33 UTC, shoom3301 commented on apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts
> +      !!tx.receipt && (tx.receipt.status === TxReceiptStatus.CONFIRMED || typeof tx.receipt.status === 'undefined')
Fixed the wrong condition.
When there is no `tx.receipt` then `isReceiptConfirmed` will be true, because tx.receipt?.status === 'undefined' is true

2024-04-02 12:33 UTC, shoom3301 commented on apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts
> +    isPending = !tx.receipt && !isTxExpired(tx, chainId)
The main chain 2

2024-04-02 13:27 UTC, elena-zh commented
Hey @shoom3301 , cool!
But this is what I see right now: pending approval TX is not removed from the Swap form, however more than 5 mins have passed from the initiation time. 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/d72a4361-021e-4304-a068-4b34f9b58490)

But! The TX is labeled as Expired in the Account modal
![image](https://github.com/cowprotocol/cowswap/assets/70885163/de0ba524-94d1-49a1-98fa-aa79a773c6d3)

2024-04-03 08:01 UTC, shoom3301 commented
@elena-zh thank you! Nice catch! Fixed it

2024-04-04 11:17 UTC, anxolin reviewed
With this PR im a bit concern we create this fake final state. 

It's canceled if the nonce progresses but the TX is not executed, but is not time related.

What is exactly the issue to solve. Because you mentioned the wallet returns a hash, is just that the TX takes too long to execute, and that's alright

If the issue is we need a way to launch the approval again, we might need to find some other way imo

2024-04-04 13:56 UTC, shoom3301 commented
@anxolin yep, I've got rid of this fake state:
https://github.com/cowprotocol/cowswap/pull/4140#issuecomment-2036854210

2024-04-04 15:58 UTC, elena-zh requested changes
Hey @shoom3301 , now event successful transaction is labeled as failed :( 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/d1f529bf-5eec-411b-bf65-005c81520e28)

2024-04-05 06:01 UTC, shoom3301 commented
@elena-zh on your screenshot I see that Safe said the transaction is not found, because of it we marked it as failed.
Could give the Safe address please?

<img width="1273" alt="image" src="https://github.com/cowprotocol/cowswap/assets/7122625/e4b7f042-2655-4d6d-8ffd-c4eaecf129fb">

2024-04-05 07:14 UTC, merged

2024-04-05 08:10 UTC, elena-zh commented
> @elena-zh on your screenshot I see that Safe said the transaction is not found, because of it we marked it as failed. Could give the Safe address please?
> 
> <img alt="image" width="1273" src="https://private-user-images.githubusercontent.com/7122625/319874624-e4b7f042-2655-4d6d-8ffd-c4eaecf129fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDQ4NjUsIm5iZiI6MTcxMjMwNDU2NSwicGF0aCI6Ii83MTIyNjI1LzMxOTg3NDYyNC1lNGI3ZjA0Mi0yNjU1LTRkNmQtOGZmZC1jNGVhZWNmMTI5ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDVUMDgwOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWViMzE5OWQ2MDY5MDk1MTc4YWI1OTU0Y2U0NTBkYmY3NDEyY2E3MjQ2ZDlmMjhkZjEwY2U3NzMzNTllMTQ5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HnljHN8voEupSw82DgOE9DGb7Td_SQlv_JD2lZxBgVo">

Safe [address ](https://app.safe.global/apps/open?safe=sep:0x8FAb71C0d4272698A3B2d1F3Ed5FC3c1B9b3E531&appUrl=https%3A%2F%2Fswap-dev-git-fix-3860-gnosis-chain-permits-cowswap.vercel.app)

And the last TX I placed was a successful one