feat(wallets): add coinshift to allowed domains
cowprotocol/cowswap pull request #4931
Opened 2024-10-01 07:49 UTC by shoom3301

# Summary

2024-10-07 10:39 UTC, elena-zh requested changes
Hey @shoom3301 , when I open the app inside the Safe it appears to be not connected 
![image](https://github.com/user-attachments/assets/c3346ee9-c5b5-466d-87e9-cd7c40cf81a7)
![image](https://github.com/user-attachments/assets/b5f0e867-4419-4ec4-a440-ad6546cc9dcc)
Same for the widget
![image](https://github.com/user-attachments/assets/eed0e750-ecaf-434d-955b-6798f41424e5)

Could you please take a look at it?

2024-12-03 10:59 UTC, shoom3301 commented
@elena-zh fixed

2024-12-03 14:58 UTC, shoom3301 commented
@elena-zh it is ok, the widget configurator is not suposed to work in Safe Apps

2024-12-03 15:15 UTC, elena-zh approved these changes
Not an issue according to this [discussion ](https://cowservices.slack.com/archives/C0361CDG8GP/p1733238527123859?thread_ts=1733238242.074289&cid=C0361CDG8GP)

2024-12-05 08:39 UTC, alfetopito approved these changes

2024-12-17 11:05 UTC, shoom3301 commented on libs/wallet/src/web3-react/connection/safe.tsx
> +                allowedDomains: [/app\.safe\.global$/, /(.+\.)?coinshift\.global$/, /localhost:5173$/],
Yes, in the guide: https://intercom.help/coinshift-d769bc455cc3/en/articles/9779372-a-guide-to-integrate-your-dapp-with-coinshift-personal

2024-12-17 11:20 UTC, merged