feat: prevent adding unsupported hooks for your wallet
cowprotocol/cowswap pull request #5020
Opened 2024-10-22 15:56 UTC by fairlighteth

# Summary

- Prevents the user from being able to add unsupported hooks for their current connected wallet
- Visually indicates which hooks are not compatible
- Sorts the hooks list automatically by supported first -> then unsupported
- Hooks without specific support defined (n/a) are considered 'compatible'

**EOA connected:**
<img width="514" alt="Screenshot 2024-10-22 at 16 52 30" src="https://github.com/user-attachments/assets/736a9922-d29d-4112-856f-bdb8dc6237d6">

**Safe connected:**
 
https://github.com/user-attachments/assets/ae523d84-4e26-4038-a8d2-cece770f1152

2024-10-23 07:07 UTC, shoom3301 commented on apps/cowswap-frontend/src/modules/hooksStore/pure/HookDetailHeader/index.tsx
> +  const isCompatible =
The code is duplicated in `HookListItem` component, I suggest to move it in a util function

2024-10-23 07:08 UTC, shoom3301 commented on apps/cowswap-frontend/src/modules/hooksStore/containers/HookRegistryList/index.tsx
> +              walletType={
`walletType={walletType}`

2024-10-23 07:09 UTC, shoom3301 commented on apps/cowswap-frontend/src/modules/hooksStore/containers/HookRegistryList/index.tsx
> +  }, [filteredDapps, isSmartContractWallet])
`walletType` is not present in `useMemo()` deps

2024-10-23 07:09 UTC, shoom3301 commented on apps/cowswap-frontend/src/modules/hooksStore/containers/HookRegistryList/index.tsx
> +  }, [filteredDapps, isSmartContractWallet])
And `isSmartContractWallet` is not needed there

2024-10-23 10:29 UTC, elena-zh requested changes
Hey @fairlighteth , great, thank you!
However, in this PR it is impossible to add a custom hook even if a wallet type is allowed for it. 
![impossible to add](https://github.com/user-attachments/assets/0ec87fe8-8fe5-4f1a-91b8-24f27b59ebcf)

Please see #4910 : you can find there instructions how to get a custom hook link.

2024-10-23 15:17 UTC, fairlighteth commented
@elena-zh address your comment, should work as expected now:
<img width="562" alt="Screenshot 2024-10-23 at 16 13 49" src="https://github.com/user-attachments/assets/60e71197-1faa-432d-9694-fbfbd6640064">
<img width="611" alt="Screenshot 2024-10-23 at 16 13 37" src="https://github.com/user-attachments/assets/cc1522b7-9f09-4fba-9fe3-83955ac26c8b">
<img width="536" alt="Screenshot 2024-10-23 at 16 12 47" src="https://github.com/user-attachments/assets/e73b0470-9c22-459b-96a3-4de0ecd90af4">

2024-10-23 15:18 UTC, fairlighteth commented
@shoom3301 addressed your comments and did some refactoring in general.

2024-10-23 15:40 UTC, elena-zh approved these changes
Works now, thank you!

2024-10-24 14:29 UTC, shoom3301 approved these changes

2024-10-28 14:23 UTC, merged