feat: replace fortune cookies
cowprotocol/cowswap pull request #5050
Opened 2024-10-28 17:00 UTC by fairlighteth

# Summary

- Updates the fortune cookies
- Important: To be merged after the halloween theme is not active anymore. The Halloween theme has it's own fortune cookies (https://github.com/cowprotocol/cowswap/pull/5049) that should be replaced by this.

2024-10-28 19:35 UTC, elena-zh approved these changes

2024-10-29 08:45 UTC, shoom3301 requested changes
See https://github.com/cowprotocol/cowswap/pull/5049#discussion_r1820356897

2024-10-29 09:59 UTC, fairlighteth commented
> See [#5049 (comment)](https://github.com/cowprotocol/cowswap/pull/5049#discussion_r1820356897)

Pushed an update to this.

2024-10-29 10:13 UTC, shoom3301 approved these changes

2024-11-01 08:27 UTC, shoom3301 approved these changes

2024-11-01 08:30 UTC, merged