feat(yield): use pools info from API
cowprotocol/cowswap pull request #5138
Opened 2024-11-28 11:57 UTC by shoom3301

# Summary

https://github.com/cowprotocol/bff/pull/99 - BFF

There are two new endpoints:
 - https://bff.barn.cow.fi/42161/yield/getPoolsAverageApr - returns average APR per provider
 - https://bff.barn.cow.fi/42161/yield/getPoolsInfo - returns pools info (tvl, apr, etc.)

# To Test

1. The values on UI should match values from API
2. Values should be updated after network changes

Important!
If there are some issues with data (you see it on the API response), please report it in slack channel about vampire attack.

2024-12-05 11:33 UTC, alfetopito approved these changes

2024-12-05 11:33 UTC, alfetopito commented on apps/cowswap-frontend/src/modules/yield/updaters/VampireAttackUpdater.tsx
> +      // TODO: use BFF_BASE_URL
```suggestion
```

2024-12-19 13:10 UTC, elena-zh requested changes
Hey @shoom3301 , great!
I've been able to test it on Mainnet only as data is still missing on other chains (reported it [here](https://cowservices.slack.com/archives/C07M5DZHMHC/p1734608555658349?thread_ts=1734094169.807429&cid=C07M5DZHMHC)). 
Also, provided data differs from the one that is displayed on pool provider's app (also [reported](https://cowservices.slack.com/archives/C07M5DZHMHC/p1734607904319359?thread_ts=1734433673.477769&cid=C07M5DZHMHC))
 Issues that I've faced: 
1. Some pools are missing in a token list, but they are present on the API response
![missing](https://github.com/user-attachments/assets/c1808a6e-7da0-4243-bb49-7070d9c3f494)
2. Vice versa: pool that are present in a token list, are absent in the API
![image](https://github.com/user-attachments/assets/5cd2aa41-1330-42c8-ac50-903f625e31d7)
This is resulting in many 0-data pools on the UI
![image](https://github.com/user-attachments/assets/9c3a5101-143b-4dab-89f8-d9ef50e36b3e)

3. There is an issue with decimals: it is weird to see that CoW AMM pool token 0.0% performs better :) 
![00](https://github.com/user-attachments/assets/45a4d7bd-3b2b-4a8e-bd58-738617a0f399)
![0 03](https://github.com/user-attachments/assets/a6c71bba-1948-4cda-bd1c-f38fd59e2e3a)

Thanks!

2025-01-20 11:48 UTC, shoom3301 commented
Closing the PR till we need it again

2025-01-20 11:48 UTC, closed without merging