feat: add uni v2 withdraw hook
cowprotocol/cowswap pull request #5155
Opened 2024-12-04 19:04 UTC by yvesfracari

# Summary

Add Uniswap V2 Withdraw Hook Dapp

# To Test

1- Connect your wallet and switch to any uni v2 deployed chain (Arbitrum and Mainnet)
2- In Hooks > Add Pre-Hook Action, the Uni V2 Deposit should appear in the "All hooks" section
3- Fill the form data and add the pre-hook
4- Check with the simulation feature if it is working as expected.

Notes:
- The token list should be the same as the CoW Swap Yield list.
- If the pool that you want to withdraw is not on the token list you can import it by pasting the address on the dropdown menu.
 - This feature should show an error if the pool is not a valid contract or you don't have funds.
- All the UI was already reviewed.

2024-12-05 12:20 UTC, elena-zh requested changes
Hey @yvesfracari , thank you

But I have to say that nothing is working here. 
1. I have a liquidity token on Ethereum, and it is in the Yield list. but it is not displayed in the pools list in the hook
![no pool](https://github.com/user-attachments/assets/087a860b-a5e0-4691-8578-0f78a1c62d36)
![token](https://github.com/user-attachments/assets/8b75faae-b7bc-408c-9629-05d79d43e749)
2. When I search for this pool, it shows me an error
![error loading](https://github.com/user-attachments/assets/fe62a57a-8c37-42ab-830a-0dd374cd31df)
3. Same happens on Arbitrum
4. It would be nice to add this functionality to Sepolia
5. It would be nice to truncate trailing and preceding spaces when paste an address into the search field
![spaces](https://github.com/user-attachments/assets/d41fa26a-9bbf-411a-9bd3-0f092f7382d1)
6. Overall, it would be great to add a simple validation on an address format into the field
![image](https://github.com/user-attachments/assets/5962136e-c367-4be4-83f1-a9386382eb63)

Overall, could you please check the functionality using the preview link on your side before sending it for my review? 

Thank you!

2024-12-06 11:00 UTC, alfetopito commented
Hey Pedro, I have a question about this screen:

![spaces](https://private-user-images.githubusercontent.com/70885163/392811557-d41fa26a-9bbf-411a-9bd3-0f092f7382d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODI5MDYsIm5iZiI6MTczMzQ4MjYwNiwicGF0aCI6Ii83MDg4NTE2My8zOTI4MTE1NTctZDQxZmEyNmEtOWJiZi00MTFhLTliZDMtMGYwOTJmNzM4MmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDEwNTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYzNhNjA3NTIwZDU4OGYxZmZiNWMxMzMwZTY2NWM2MzFhZjgyZWM3OGI1MzMzNDZhZGMzYWQ0YTZkMzk4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mnh3WpWg2LXXy4dXNoWIW0vYJJqtLKxBcfET_Kszr-k)

Here, it's searching by an address.
It says no results found, and it also says to search for it in the search bar.
The second phrase is a bit confusing to me. If you haven't found, would it make any difference if you search for it again?
Unless I misunderstood, I think this sentence should be removed altogether.

2024-12-06 11:56 UTC, anxolin commented
I tried to use it, but TBH not sure how 😅

I get this message when I try to use the drop-down:
<img width="613" alt="image" src="https://github.com/user-attachments/assets/83d58c28-6ad8-42c2-806b-cc32c720b88b">


Also, after a few seconds, it re-renders everything again.

I'm also not sure what the message is saying.
I guess is trying to see if I have balance on any of the pools. Imo, and this would apply to the other hooks where I also think suffer from the same issue, we should show all the pools even if there's no balance for them. The logic is very similar to our token selector, we show the balances of all tokens, but we show first in the list the ones with balance greater than zero. This way, the user understand they need to select a LP, they can see the options, and they see they cannot add the pre-hook cause their balance is zero for all of them. 

<img width="892" alt="image" src="https://github.com/user-attachments/assets/0ef951b2-da1d-4612-af18-a8255fef6b64">




In the instructions says, I should use Mainnet/Arbitrum, but I think we have UniV2 available also in Base and Sepolia. 
<img width="830" alt="image" src="https://github.com/user-attachments/assets/80855f83-ea18-408d-b8a9-3098ac6c4ec0">

2024-12-06 11:57 UTC, elena-zh requested changes
Hey @yvesfracari , 

thanks, but still:
1. Could you please clarify why this happens on console when I open the hook on Ethereum?
![mad console](https://github.com/user-attachments/assets/06cbbee0-2cfa-4ebb-a70c-f54ae720a7c2)
2. On Ethereum, I don't see my UNI pool details (however, I have an LP token there)
![eth](https://github.com/user-attachments/assets/0ed66cd8-bc3b-46de-86da-728ac2a14d86)

3. I don't see this hook on Sepolia :( 
![ho hook sepolia](https://github.com/user-attachments/assets/badc9e62-860c-4b8b-9c33-4ce4fa6501f7)
4. As Leandro pointed out in the comment above, I'm also confused with the message that is displayed by default on the list opening: I have not done anything yet, and it says about incorrect format...
![i have not done](https://github.com/user-attachments/assets/0af9d910-57a0-4e4d-84cb-d8f863f714a6)
5. As for address validation, might it be possible to show this error when a user starts typing it? Something like it is already implemented in one of vesting hooks: 
![example](https://github.com/user-attachments/assets/48c4ed30-45d5-4379-a327-49fd8a7ae2f8)
6. I've noticed that the pool's search is reset in several seconds: the loader appears, and  the search field area is closed. Could you please take a look why this happens? 
Thanks!

2024-12-06 19:23 UTC, yvesfracari commented
@anxolin @alfetopito @elena-zh Thank you all for the feedbacks.

Sorry for the errors. I will try to group the feedbacks and reply them together.

1 - Supported chains: I added the support for sepolia on the `manifest.json` but I think that the deployment wasn't updated with my latest commit (I think that someone have to approve it). I didn't added base because I thought it wasn't fully integrated yet, if you guys want I can add it.

2 - Importing and searching pools: The text field is used for both importing and search for pools. That is why I didn't implemented the suggested `invalid address format` error message and instead there is a "No pools found" message. If the user paste and address that is not a pool it should see an "Error loading new pool.".

3- Pool list: As it works on the "CoW AMM Withdraw" hook dapp, the app was loading only pools that the user has. However, now the app loads all pools and sort them (as @anxolin suggested). Since this is a long list, we're no longer displaying price information of the pools. Instead, we're showing the user balance in LP tokens. This also fix the rate limit errors that @elena-zh reported on mainnet (sorry I was testing on arb) and the re-renders reported by @anxolin .

2024-12-10 16:06 UTC, elena-zh requested changes
Hey @yvesfracari , thank you!
But still there is a bunch of issues I faced: 
1. Pool tokens balances are not displayed on Arb and Ethereum
![not 0 balance](https://github.com/user-attachments/assets/78cbd47d-abb5-4c2f-9abc-c3d67847638f)
![Screenshot_1](https://github.com/user-attachments/assets/2b404b29-131b-47bd-bbdc-9e6439fafa59)
![usd](https://github.com/user-attachments/assets/42132478-4037-465f-a917-d0ddbfbfd035)
2. Link to a pool details navigate to Balancer
![uni pool navigates to balancer](https://github.com/user-attachments/assets/6778e9c8-5b2c-46dc-8e63-d6bef81dd610)
3. When I search for a token, and a token is a LP token, it says 'not found' 
![illogical](https://github.com/user-attachments/assets/a7c38a51-8677-45ed-8243-859b6a920bfa)
4. Besides, for me it is illogical to show 'Try placing your LP token address on the search bar.' if I've already done it. I'd remove this message at all...
![remove](https://github.com/user-attachments/assets/685dd58a-1fab-43a5-b6ab-98458d1fcacd)
5. Sometimes, when I search for a LP token, I face a red error message, but IDK what is wrong here: 
![why error](https://github.com/user-attachments/assets/f59f879a-5147-4d29-93fc-29f6fe15b4b9)
Might it be possible to add explanation about the error?
5. The hook has not been added to Base (as @anxolin suggested)
6. There are a lot of v2 pools on sepolia, but nothing is displayed in the list. I assume that this is due to they are absent in the LP list. Might it be possible to fetch them? 
7. USD estimation for WETH token is missing on Sepolia
![sep usd estimation](https://github.com/user-attachments/assets/1413bb9d-f361-4f92-85d2-7471a32cf050)
8. I tried to add a hook on sepolia, but it ended up with error: 
![sepolia hook gas](https://github.com/user-attachments/assets/e1289df2-e0fc-4de9-82e1-9779933b4885)
Details: 
```
Calldata
: 
"0xa8481abe00000000000000000000000000000000000000000000000000000000000000a031373333383435323630353136000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067586f0f0000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda580000000000000000000000000000000000000000000000000000000000000720000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000240000000000000000000000000000000000000000000000000000000000000038000000000000000000000000000000000000000000000000000000000000004a0000000000000000000000000164ffe42adcf8a147090a5981ad0881cc11ecfe6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e4d505accf0000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda5800000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de290ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000000000000000000000000000000000000070c00868000000000000000000000000000000000000000000000000000000000000001c8852758c0f6da983164020656e5a3516b71f4cfe59085cb8a45476cbc7d9e7511189263771d79566a4c4d91ef9c669b67e41baea3dea8c980ff84f9772eba23700000000000000000000000000000000000000000000000000000000000000000000000000000000164ffe42adcf8a147090a5981ad0881cc11ecfe6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006423b872dd0000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda5800000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de29000000000000000000000000000000000000000000000000003ecdbf2cc5b8c7700000000000000000000000000000000000000000000000000000000000000000000000000000000164ffe42adcf8a147090a5981ad0881cc11ecfe6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000ee567fe1712faf6149d80da1e6934e354124cfe300000000000000000000000000000000000000000000000003ecdbf2cc5b8c7700000000000000000000000000000000000000000000000000000000000000000000000000000000ee567fe1712faf6149d80da1e6934e354124cfe3000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e4baa2abde0000000000000000000000007b79995e5f793a07bc00c21412e50ecae098e7f9000000000000000000000000b4f1737af37711e9a5890d9510c9bb60e170cb0d00000000000000000000000000000000000000000000000003ecdbf2cc5b8c77000000000000000000000000000000000000000000000000004657febe8d7fff00000000000000000000000000000000000000000000000036f4bf04de8bff680000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda580000000000000000000000000000000000000000000000000000000067586eea0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000419cdcedb3e1dbcd31c91d1c8b9cb3360acd78c1a3b765e3ff0480450f225db4623a2d78b9e7b759f93b21b9c736f0e82e4d85a79c417eaa0eec13e1e036fe92901c000000000000000000000000000000000000000000000000000000000000000001"
chainId
: 
11155111
currentBlock
: 
7251147n
currentTimestamp
: 
1733845271
target
: 
"0x00E989b87700514118Fa55326CD1cCE82faebEF6"
```


Thanks

2024-12-11 14:37 UTC, yvesfracari commented
@elena-zh Thanks for the feedbacks!

1- It was a rounding issue. Now should be ok.
2- Fixed.
3- I try to fix some bugs related to inconsistency of this search. Now should be fixed. Here is a video of my tests: https://www.loom.com/share/7ae2d355d5574c3da77fe0d0e61e8b26
4- Removed the second line of the message.
5- Now we're displaying more details of the error that happened.
6- Now it should be added on Base.
7- That is correct. On my understanding, I think that we agreed on using the same list of CoW Swap was using. If the pools were added there it should show up here too.
8- We're using CoW API price information (what I think that is ok on this case). For sepolia it is common some token missing price information, if it happens on a non test net we can change our approach.
9- As I mentioned in our private chat, the pool that was used to test was not created by the official factory. I added a validation about this on the pool importing. However, now the pool is already on your local storage, so to test I recommend you to clear and try to import it again.

By the way, all these replies are related with my local tests. Can you authorize the new deployment so I can test?

2024-12-12 11:03 UTC, shoom3301 commented
@yvesfracari could you pull the latest changes from `develop` into this PR please?

2024-12-12 13:16 UTC, elena-zh commented
Hi @yvesfracari , thank you for your fixes!

Still, some issues: 
1. Hook on Base: 
 - it does not change balance when add it
![base balance change](https://github.com/user-attachments/assets/44db0ac4-3100-4fdd-90c7-fcf80ccecfb2)

 - looks like the hook was not executed with my [order](https://dev.explorer.cow.fi/base/orders/0x99506537f43af6d24400d791cb7b294fc54af620469f109feff70612bc8c75b49fa3c00a92ec5f96b1ad2527ab41b3932efeda58675ae760?tab=overview). Here is the [TX](https://basescan.org/tx/0x0628df0da5c35dea8d89f39d05a7076d25a10695ed9662f0f1e42c91c095488d). Pool token is this [one](https://app.uniswap.org/positions/v2/base/0x88A43bbDF9D098eEC7bCEda4e2494615dfD9bB9C)

2. When 'no search results' is displayed, the UI re-renders each 10-20 seconds --> it does not look good
3. Also, when a hooks is being loaded, it is loaded twice. I mean: the search page appears, then the loader appears once again. It would be nice to show a loaded only once 
4. Could you please remove red background from error messages?  :) 
![remove the background](https://github.com/user-attachments/assets/cdb4051d-217f-49dc-9b8c-bec99baaf61a)

Thank you

2024-12-12 15:51 UTC, yvesfracari commented
@elena-zh Thanks for the feedback. The errors 2-4 are fixed. As I mentioned on our chat, the 1 error is due to an undeployed contract on Base. I think that we can test it again once it is deployed.

2024-12-16 13:01 UTC, elena-zh commented
Hey @yvesfracari , thank you. 

The contract on Base has been deployed, hooks are working there now. 

As for issues: 
1. Could you please check why I cannot see my pool tokens on Arbitrum? 
![image](https://github.com/user-attachments/assets/a575ae5d-7517-4223-9f4e-34d2a92b1ae2)
![image](https://github.com/user-attachments/assets/5b01a7d6-2a1b-4190-8216-3b40c5260424)

2. Could you please reset search results once I close the Search area and navigate back to the 'Select pool' state?
![quit](https://github.com/user-attachments/assets/922823f1-7588-4d95-b764-9e2b7e9b26de)
![reset](https://github.com/user-attachments/assets/25d42e4a-7e5c-47e1-8f90-09a6dbe80c3c)


Thanks!

2024-12-16 21:22 UTC, yvesfracari commented
Hey @elena-zh !

Currently, there is only 1 Uni v2 pool on the CoW LP Token List for arbitrum. The pools that you presented are CoW AMMs.

![image](https://github.com/user-attachments/assets/1230e179-7605-4df7-bda4-c2451468760c)

About resetting the search field, it is done!

2024-12-17 12:01 UTC, elena-zh approved these changes
Thank you

2025-01-20 11:49 UTC, shoom3301 approved these changes

2025-01-20 11:51 UTC, merged