Improve cow message
cowprotocol/cowswap pull request #609
Opened 2022-05-31 11:18 UTC by anxolin

# Summary

Small experiment on how to increase the awareness of what is a CoW

Obviously could have better styling, I would love @fairlighteth to help if possible.
Small improvements that come to mind, is to proved a 360º effect on the swap icon from time to time. Also, probably the presentation of the message. Maybe the dancing cows could look better if they are smaller?

Note: For this PR right now i did a change so its always in looking for COWs state, however normally it last 30s. We will need to undo the change i did to make it behave like this.

![May-31-2022 12-05-21](https://user-images.githubusercontent.com/2352112/171161607-1502f82d-a4f4-4137-bac2-b9661ce1c48f.gif)

# To Test

1.  Make a trade
2.  Observe the progress bar

2022-06-02 13:41 UTC, anxolin commented
@alongoni @ramirotw , I think is better if you take this one over. Its best I'm happy to merge this and then you can reiterate in how we present these longer messages. We were going to take a look to this, but theres no capacity from our end right now.

2022-06-14 11:06 UTC, ramirotw commented
@alongoni FYI I updated the base branch, cleaned-up and solved conflicts, also did a rebase so if you have issues later with some local changes, ping me

2022-06-24 10:11 UTC, alfetopito reviewed
I love this!

Left a few small nitpicks in the code.

Also one small difference between the modal vs activity details

Modal:
![Screen Shot 2022-06-24 at 11 09 51](https://user-images.githubusercontent.com/43217/175514299-be7890a9-e919-4e43-85e9-28cd9ea12d71.png)
Activity details:
![Screen Shot 2022-06-24 at 11 04 10](https://user-images.githubusercontent.com/43217/175514311-831461cd-cef9-4353-adb2-d2509819b9e1.png)

2022-06-24 12:15 UTC, elena-zh requested changes
Hey @alongoni , @ramirotw , great changes!!

However, a list of issues from my side: 
1. Confirmation modal does not appear when place an order in Expert mode!
2. The modal remains to be displayed when an order is expired
![expired](https://user-images.githubusercontent.com/70885163/175529796-d103bd74-6750-4711-bf29-4b901bbe3836.jpg) . It would be nice to hide a progress bar in this case and tell a user that the order is expired. 
3. The same is for Cancel status: a user can cancel an order from the modal, and from another browser (currently, order info is synced between devices). So when an order is cancelling and cancelled, it would be great to close this modal at least. Or it would be great to say a user that order is cancelling/cancelled, and stop showing the progress bar. 
![cancelling](https://user-images.githubusercontent.com/70885163/175530224-198d3c0d-3ff3-4ecf-9d8f-d8e7ea974ac4.jpg)
![cancell](https://user-images.githubusercontent.com/70885163/175530313-79daf3b8-56ab-44bc-8250-61be09f1f885.jpg)
![cancelled](https://user-images.githubusercontent.com/70885163/175530326-d99fc61b-da84-447c-89a4-0c0add9504b5.jpg)
4. When connected to Safe wallet, the progress bar is displayed when an order is in Signing state. Progress bar should appear when an order is in 'Open' . Discussed in https://github.com/cowprotocol/cowswap/issues/615#issuecomment-1160339549
![safe activity](https://user-images.githubusercontent.com/70885163/175530607-11f7ab57-6ea7-4ba8-96e2-83322a1a60af.jpg)
![when signed](https://user-images.githubusercontent.com/70885163/175530610-00e55632-90ed-4d50-ae87-e80d34b1fa62.jpg)
![safe - usual modal](https://user-images.githubusercontent.com/70885163/175530662-c5151610-e124-4917-93f0-e19248f6dd0f.jpg)

5. Modal does not look good when screen width is in [724-950] px
![Screenshot_4](https://user-images.githubusercontent.com/70885163/175530839-677423df-c3fa-4077-b131-458e0cc3ecbb.jpg)

6. I'm not sire about it, but shouldn't we show different liquidity providers for GC? 
![image](https://user-images.githubusercontent.com/70885163/175530974-4cffca1e-ba8a-4d87-ac5d-295e38206154.png)

7. A bit sophisticated case, but I noticed that when place 2 orders one after another, the conf. and activity modals show different states for progress bar. Firstly, I thought that it shows the 1st order bar (instead of the last), but then I notices that the bar on the conf.modal "lives it own life" and does not match statuses in the activity modal.
![diff statuses](https://user-images.githubusercontent.com/70885163/175531457-eb332288-3844-4f9f-9ffa-1628203b0757.jpg)
![diff](https://user-images.githubusercontent.com/70885163/175531476-2ee9153d-8512-4f93-b6dc-dcc3517cc152.jpg)
I assume, we should show a progress bar for the last order 
8. I noticed, that 'Price out of market' message may be changed to 'Longer than usual' in a while. Is it OK?
9. I noticed that 'Cancel' order links colors are different in the conf. and activity modals. Frakly, it looks good to me, however, I would better clarify
![diff colors ok](https://user-images.githubusercontent.com/70885163/175531840-8b7c6411-290f-4e0d-8f02-a4b8dee5f377.jpg)

10. Cancel order button shifted a bit from the main text in a mobile device
![image](https://user-images.githubusercontent.com/70885163/175537758-339212e1-a4ab-41da-bec2-fb698f2ffaa7.png)

11. And there is no pop-up saying that a user can track the order execution status when closing the confirmation modal. Will it be implemented in another PR? 

Thanks!

2022-06-24 13:40 UTC, elena-zh commented
I have created a separate issue  #745  for the case 11

2022-06-24 22:52 UTC, alongoni commented
Thanks for the feedback! I've tackle all styles issues. @ramirotw will continue with the missing points (code improvements and bugs)

2022-06-30 09:18 UTC, ramirotw commented on src/custom/components/AccountDetails/Transaction/OrderProgressBar/index.tsx
> +        validTo: new Date((order.validTo as number) * 1000),
it's a Timestamp and 
<img width="957" alt="image" src="https://user-images.githubusercontent.com/3328006/176640979-b166bdd7-fe0c-4531-95ac-0b7ae57f29f2.png">

2022-07-04 12:24 UTC, ramirotw commented on src/custom/components/AccountDetails/Transaction/OrderProgressBar/index.tsx
> +                </p>*/}
Not really, we should probably add this in another PR. The issue with the current price is that is not saved on the state when fetched to toggle the isUnfillable flag. I didn't want to add more complexity to the PR so I didn't include any changes to handle this.

2022-07-04 16:26 UTC, elena-zh commented
Hey @ramirotw , @alongoni great changes. 
I have retested all cases except the 1st one, and Gnosis safe case. 
And here is my feedback: 
1. Progress bar starts is already moving when I sign an order. The it goes back. The time depends on the time I take for signing an order (the request is sent to the wallet, but not yet signed). See the [video](https://watch.screencastify.com/v/YK1JNEhokCYAbreLkNgl). I expect to see the bar from the start when I sign an order. 
2. Coincidence of wants link behaves differently on hover action in the modal and in the activity list
![Screenshot_3](https://user-images.githubusercontent.com/70885163/177191402-cfb02c66-4435-4613-b97f-e49164f4c4f5.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/70885163/177191409-7bdce09f-79b1-4bea-99a2-4d761bbbd5db.jpg)
3. Cancel link is flashing in the activity modal when hover a mouse on it
![flash](https://user-images.githubusercontent.com/70885163/177191688-48a35d6f-ca22-416e-aa6b-03e4c7e3ca30.jpg)

5. I have not noticed 'Price out of range' message. I placed several orders that should affect a market price, and an opened order hang for 10 minutes with another message, not 'price out of range'
![more than 6, no price out of range](https://user-images.githubusercontent.com/70885163/177191780-d1d356e6-9a5b-4599-ae77-c258cfbb17db.jpg)
6. When an order is 'cancelling', the modal with progress bar still shows that it is executed. Accidentally, the modal might be changed to 'Transaction Submitted' state until the order is cancelled/traded. I think, we should add 'Cancelling' state
![cancelling](https://user-images.githubusercontent.com/70885163/177191943-a70382b8-0871-4941-b99b-716de102c5fb.jpg)
![cancellint](https://user-images.githubusercontent.com/70885163/177191955-38aee6fd-2111-4f54-9540-7350c8a50450.jpg)

7. Maybe we should not name the modal 'Transaction', as we are placing orders, and orders are displayed on Explorer. WDYT? 
![image](https://user-images.githubusercontent.com/70885163/177192082-2aae032a-2a82-44cb-b354-d16abd677fe8.png)
![image](https://user-images.githubusercontent.com/70885163/177192133-9a96e039-d65a-480d-879a-502f6acaf7bd.png)
![image](https://user-images.githubusercontent.com/70885163/177192152-219fb1c6-9f06-4ed1-b303-6d97b8acbd6f.png)

Thanks!

2022-07-04 17:30 UTC, ramirotw commented
Thanks @elena-zh for the feedback.

> 1. Progress bar starts is already moving when I sign an order. The it goes back. The time depends on the time I take for signing an order (the request is sent to the wallet, but not yet signed). See the [video](https://watch.screencastify.com/v/YK1JNEhokCYAbreLkNgl). I expect to see the bar from the start when I sign an order.

This is side effect of the fix for:

> A bit sophisticated case, but I noticed that when place 2 orders one after another, the conf. and activity modals show different states for progress bar. Firstly, I thought that it shows the 1st order bar (instead of the last), but then I notices that the bar on the conf.modal "lives it own life" and does not match statuses in the activity modal.

The original problem was that the `creationTime` field from the order is created dynamically and persisted in the storage. If you happen to be using 2 tabs that `creationTime` value has a small difference in seconds when loaded into redux. During the tests I did it was something between 3-5 seconds, small difference but enough for the progress bar percentage to be off. To kind of fix that issue, I first use the `creationTime` as it is a local value, and then when the order details are fetched from the API I use the `creationDate` from the response which is consistent, here it's when you see the jump to the beginning.

2022-07-04 17:37 UTC, ramirotw commented
> ![image](https://user-images.githubusercontent.com/3328006/177199038-1f6773b0-aa2b-4f1d-bb24-7024ef6d9f00.png)

We don't have intermediate on the progress bar, what should we do for a cancelling state? hide it?

2022-07-05 08:35 UTC, elena-zh commented
> Thanks @elena-zh for the feedback.
> 
> > 1. Progress bar starts is already moving when I sign an order. The it goes back. The time depends on the time I take for signing an order (the request is sent to the wallet, but not yet signed). See the [video](https://watch.screencastify.com/v/YK1JNEhokCYAbreLkNgl). I expect to see the bar from the start when I sign an order.
> 
> This is side effect of the fix for:
> 
> > A bit sophisticated case, but I noticed that when place 2 orders one after another, the conf. and activity modals show different states for progress bar. Firstly, I thought that it shows the 1st order bar (instead of the last), but then I notices that the bar on the conf.modal "lives it own life" and does not match statuses in the activity modal.
> 
> The original problem was that the `creationTime` field from the order is created dynamically and persisted in the storage. If you happen to be using 2 tabs that `creationTime` value has a small difference in seconds when loaded into redux. During the tests I did it was something between 3-5 seconds, small difference but enough for the progress bar percentage to be off. To kind of fix that issue, I first use the `creationTime` as it is a local value, and then when the order details are fetched from the API I use the `creationDate` from the response which is consistent, here it's when you see the jump to the beginning.

Thanks, @ramirotw . for explanation. But maybe as another option we should not allow the progress bar to move until the data is recorded into redux, WDYT?

2022-07-05 08:38 UTC, elena-zh commented
> > ![image](https://user-images.githubusercontent.com/3328006/177199038-1f6773b0-aa2b-4f1d-bb24-7024ef6d9f00.png)
> 
> We don't have intermediate on the progress bar, what should we do for a cancelling state? hide it?

As an option, we can show something like a message 'Order cancel request is submitted' or so instead of the progress bar.

2022-07-05 10:50 UTC, elena-zh commented
Hey @alongoni , I have retested changes in a mobile version, and have noticed that Cancel order button is still shifted
![image](https://user-images.githubusercontent.com/70885163/177311758-a9915408-83b0-4c0c-aa4d-82c35fca419e.png)

It is also shifted in 'longer than usual' message. 
Could you please take a look at it? 

Thanks

2022-07-05 11:17 UTC, ramirotw commented on src/custom/utils/trade.ts
> +  const creationTime = new Date().toISOString()
moved this after the signing is done to reduce the difference with the `creationDate` field from the API if the user takes a few seconds to sign.

2022-07-05 12:14 UTC, elena-zh commented
Hey @ramirotw , thank you! The bar is not moving back now, ang the modal name looks great from my perspective.
Cancelling order functionality works fine besides the case that the progress bar modal might be updated with a new status within 30 seconds. Also. I'd remove 'is' from the modal name, as we do not use it for all the rest modal names (Order Cancelled, Order Submitted, Order Expired, etc.)
![is](https://user-images.githubusercontent.com/70885163/177324373-7f2fb495-7821-448e-a6e6-772dbf3326e0.jpg)

2 more cases I'd like to draw your attention: 
1. Progress bar icon now is starting to move from outside of the bar. Once I caught it even outside the modal area. Could we please fix it somehow?
![outside](https://user-images.githubusercontent.com/70885163/177324630-287f9d3f-1f20-4612-8a80-c50293811320.jpg)
2. Price out of range message is displayed in the Progress bar modal, but at the same time 'order is taking longer than usual' is displayed in the activity modal for the same order. Can we align these messages, please?
![diff statuses](https://user-images.githubusercontent.com/70885163/177324832-db6f7cb8-6acb-41f0-bd5b-80c925dc2b0c.jpg)

Thank you!

2022-07-05 12:49 UTC, ramirotw commented
> 2\. Price out of range message is displayed in the Progress bar modal, but at the same time 'order is taking longer than usual' is displayed in the activity modal for the same order. Can we align these messages, please?
>     ![diff statuses](https://user-images.githubusercontent.com/70885163/177324832-db6f7cb8-6acb-41f0-bd5b-80c925dc2b0c.jpg)

That's weird. I imagine this has something to do with which tab has the focus as maybe the state is not updated for that one? could you try to see if this happens between two devices? mobile phone and laptop/desktop?

Regarding the other issue, will take a look.

2022-07-05 12:55 UTC, elena-zh commented
@ramirotw , both windows were focused (one after another), as I was traying to do a screenshot that contains both tabs.

2022-07-05 13:41 UTC, elena-zh commented
@ramirotw , the issue with different messages is also reproducible when place an order in 1 device, and track it in activity modal in another device
 - mobile phone: 
![image](https://user-images.githubusercontent.com/70885163/177341624-5cc87d62-a24f-4a11-997f-e4a0af21b6d3.png)

the same wallet connected in desktop:
![ьуыы](https://user-images.githubusercontent.com/70885163/177341771-27b8e7db-167a-4d4e-96eb-a7c0b3db99c1.jpg)

2022-07-06 15:33 UTC, elena-zh commented
Hey @alongoni , links color looks good now!

As for for the Cancel order links, so this is how they look like now: 
![image](https://user-images.githubusercontent.com/70885163/177588477-506632ba-2262-4efb-8401-1498ef9b4f08.png)
![image](https://user-images.githubusercontent.com/70885163/177588524-d9b28c5a-8699-484a-b7ff-94f2e4ebbaf8.png)

2022-07-07 14:01 UTC, elena-zh commented
> @ramirotw , the issue with different messages is also reproducible when place an order in 1 device, and track it in activity modal in another device
> 
> * mobile phone:
>   ![image](https://user-images.githubusercontent.com/70885163/177341624-5cc87d62-a24f-4a11-997f-e4a0af21b6d3.png)
> 
> the same wallet connected in desktop: ![ьуыы](https://user-images.githubusercontent.com/70885163/177341771-27b8e7db-167a-4d4e-96eb-a7c0b3db99c1.jpg)

I have created a separate issue for this case https://github.com/cowprotocol/cowswap/issues/789

2022-07-08 11:36 UTC, elena-zh commented
Hey @ramirotw , I'm still testing (need to check other SC wallets), but the issue I have noticed that Progress bar appears and is removed from the confirmation modal when transaction is signed and executed. 
Then, it is blinking when I open Activity modal. 
See the video: https://watch.screencastify.com/v/MWvuTN42VJcg6phYWr3n

Btw, a similar issue I reported for the Cancel button #702 , but the priority was low as 'Cancel' button is not so visible as the progress bar

2022-07-08 11:44 UTC, elena-zh commented
Also, still COW icon starts moving from outside progress bar area. 

And cancel button is still blinking when hover a mouse on it https://watch.screencastify.com/v/RxAWdu0wNGVieuS0uklx . Let me know whether I need to create a separate issue for this in case we decide to fix it a bit later.

2022-07-08 13:13 UTC, elena-zh commented
> And cancel button is still blinking when hover a mouse on it https://watch.screencastify.com/v/RxAWdu0wNGVieuS0uklx . Let me know whether I need to create a separate issue for this in case we decide to fix it a bit later.

Here is a separate issue for this #793

2022-07-11 08:58 UTC, elena-zh commented
I have retested the bar with another SC wallet (Argent), and have not encountered any issues with it (no progress bar there). 

Also, I still see that the progress bar icon starts from outside bar's area. Especially it is visible on mobile devices: 
![image](https://user-images.githubusercontent.com/70885163/178227579-abd4479b-7c3a-48c0-aba4-499923dc95f8.png)

2022-07-11 08:58 UTC, alfetopito commented
> > Hey @ramirotw , I'm still testing (need to check other SC wallets), but the issue I have noticed that Progress bar appears and is removed from the confirmation modal when transaction is signed and executed.
> > Then, it is blinking when I open Activity modal.
> > See the video: https://watch.screencastify.com/v/MWvuTN42VJcg6phYWr3n
> 
> The hook that detects if the current wallet is a contract wallet goes through different states before it finally detects wether it is or not. Not sure how to solve this at this point.

Can you start the activity as disabled until you get a concrete answer from the smart contract hook to then decide if it should be shown or continue hidden?

2022-07-12 11:53 UTC, ramirotw commented
> Can you start the activity as disabled until you get a concrete answer from the smart contract hook to then decide if it should be shown or continue hidden?

I can't think of a good solution that doesn't imply just delaying showing the progress bar until we are confident the `isSmartContractWallet` value is settled. During my tests the value was settled in less than a second, so maybe 2 seconds will be enough.

I tested it through Wallet Connect and there's no other hint rather than `isSmartContractWallet` when the state changes.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/3328006/178482122-197c78a6-bb3d-414a-a02a-38476379fd5c.png">

2022-07-12 14:02 UTC, elena-zh commented
> video: https://watch.screencastify.com/v/MWvuTN42VJcg6phYWr3n

I have updated #702 issue description and added the progress bar issue there. So both that cases will be addresses a bit later in a separate PR.

2022-07-13 07:18 UTC, elena-zh approved these changes
Changes LGTM now!

However, still I can face some issues: 
 - Progress bar can start moving with a delay up to 7 seconds (Mainnet)
 - https://github.com/cowprotocol/cowswap/issues/674#issuecomment-1182852959 - it is a known issue, but now this message has become more visible as the status is displayed on an order confirmation modal now
 - https://github.com/cowprotocol/cowswap/issues/702 - blinking progress bar issue in Gnosis safe (agreed to fix it later)
 - https://github.com/cowprotocol/cowswap/issues/789 - edge case when track an order execution on 2 devices
 - 
 -

2022-07-13 09:57 UTC, merged